# Generated by Django 5.2.8 on 2025-12-19 00:34

# CORREÇÃO: Caminho atualizado para a subpasta samples
import core.models.samples.sample_files
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biobank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('private', 'Privado'), ('biobank', 'Restrito ao Biobank'), ('public', 'Público')], default='biobank', help_text='Define quem pode visualizar este Biobank', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o Biobank está ativo para uso')),
                ('owner', models.ForeignKey(help_text='Curador responsável pelo Biobank', on_delete=django.db.models.deletion.PROTECT, related_name='owned_biobanks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Privada'), ('group', 'Grupo de pesquisa'), ('biobank', 'Biobank'), ('public', 'Pública')], default='private', help_text='Define quem pode visualizar esta coleção', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a Collection está ativa para uso')),
                ('biobank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.biobank')),
                ('owner', models.ForeignKey(help_text='Responsável científico pela coleção', on_delete=django.db.models.deletion.PROTECT, related_name='owned_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Orientador'), ('editor', 'Editor'), ('viewer', 'Visualizador')], default='viewer', max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão da Collection',
                'verbose_name_plural': 'Permissões da Collection',
                'ordering': ['role', 'user__username'],
                'unique_together': {('user', 'collection')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='collections', through='core.CollectionUserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KeywordValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='collections', to='core.keywordvalue'),
        ),
        migrations.AddField(
            model_name='biobank',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='biobanks', to='core.keywordvalue'),
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do grupo de pesquisa', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do grupo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(help_text='Coordenador do grupo (pesquisador principal)', on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_research_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Membros do grupo de pesquisa', related_name='research_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Privada'), ('group', 'Grupo de pesquisa'), ('biobank', 'Biobank'), ('public', 'Pública')], default='private', help_text='Define quem pode visualizar esta amostra', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biobank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='core.biobank')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='core.collection')),
                ('keyword_values', models.ManyToManyField(blank=True, related_name='samples', to='core.keywordvalue')),
                ('owner', models.ForeignKey(help_text='Responsável pela amostra', on_delete=django.db.models.deletion.PROTECT, related_name='owned_samples', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='samples', to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Entrada'), ('freeze', 'Congelamento'), ('thaw', 'Descongelamento'), ('transfer', 'Transferência')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='Usuário que realizou o evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_events', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # CORREÇÃO: Referência de função atualizada para o novo caminho
                ('file', models.FileField(upload_to=core.models.samples.sample_files.sample_file_upload_to)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.sample')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='collections', to='core.tag'),
        ),
        migrations.AddField(
            model_name='biobank',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='biobanks', to='core.tag'),
        ),
        migrations.CreateModel(
            name='BiobankUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biobank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.biobank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biobank_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão do Biobank',
                'verbose_name_plural': 'Permissões do Biobank',
                'ordering': ['role', 'user__username'],
                'unique_together': {('user', 'biobank')},
            },
        ),
    ]
