# Generated by Django 5.2.8 on 2025-12-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_active_to_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobank',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço físico do Biobank', max_length=255),
        ),
        migrations.AddField(
            model_name='biobank',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude geográfica (WGS84)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='biobank',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude geográfica (WGS84)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='country',
            field=models.CharField(help_text='País onde o Biobank está localizado', max_length=100),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='institution',
            field=models.CharField(help_text='Instituição responsável pelo Biobank', max_length=200),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='Keywords (pares chave/valor) do Biobank', related_name='biobanks', to='core.keywordvalue'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='name',
            field=models.CharField(help_text='Nome oficial do Biobank', max_length=200),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags categóricas associadas ao Biobank', related_name='biobanks', to='core.tag'),
        ),
    ]
