# Generated by Django 5.2.8 on 2025-12-23 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_biobank_address_biobank_latitude_biobank_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biobank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='biobank',
            name='country',
        ),
        migrations.AddField(
            model_name='biobank',
            name='location_label',
            field=models.CharField(blank=True, help_text='Human readable location from map search', max_length=255),
        ),
        migrations.AddField(
            model_name='biobank',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the Biobank'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='biobanks', to='core.keywordvalue'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_biobanks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='biobanks', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privado'), ('biobank', 'Restrito ao Biobank'), ('public', 'Público')], default='biobank', max_length=20),
        ),
    ]
