# Generated by Django 5.2.8 on 2026-01-14 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_biobank_address_remove_biobank_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='keyword_values',
            new_name='keywords',
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Coleção à qual a amostra pertence (opcional para amostras avulsas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='core.collection'),
        ),
    ]
