# Generated by Django 5.2.8 on 2026-01-14 01:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_keyword_values_sample_keywords_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='samplefile',
            old_name='file_type',
            new_name='mime_type',
        ),
        migrations.RemoveField(
            model_name='biobank',
            name='notes',
        ),
        migrations.AddField(
            model_name='biobank',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição institucional do Biobanco', null=True),
        ),
        migrations.AddField(
            model_name='biobank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot da localização física (Freezer/Rack/Box)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando Recebimento'), ('qc', 'Em Controle de Qualidade'), ('available', 'Disponível / Aprovada'), ('rejected', 'Rejeitada / Inviável'), ('depleted', 'Exaurida')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='samplefile',
            name='category',
            field=models.CharField(choices=[('image', 'Imagem (Microscopia/Gel)'), ('table', 'Tabela (CSV/Excel)'), ('sequence', 'Sequência (FASTA/FASTQ)'), ('pdf', 'Documento PDF'), ('raw', 'Dados Brutos / Outros')], default='raw', max_length=20),
        ),
        migrations.AddField(
            model_name='samplefile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o Biobanco está operacional'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='location_label',
            field=models.CharField(blank=True, help_text='Endereço legível (Ex: Prédio da Manutenção - IQ-USP)', max_length=255),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='owner',
            field=models.ForeignKey(help_text='Gestor principal do Biobanco', on_delete=django.db.models.deletion.PROTECT, related_name='owned_biobanks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Finalidade científica da coleção', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se a Collection está ativa para novos cadastros'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='collections_membership', through='core.CollectionUserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(help_text='Responsável científico/PI pela coleção', on_delete=django.db.models.deletion.PROTECT, related_name='owned_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privada'), ('group', 'Grupo de pesquisa (Consórcio)'), ('biobank', 'Biobank'), ('public', 'Pública (Catálogo Externo)')], default='private', help_text='Define quem pode visualizar os metadados desta coleção', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('freeze', 'Congelamento'), ('thaw', 'Descongelamento'), ('transfer', 'Transferência (Movimentação)'), ('qc_check', 'Controle de Qualidade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, help_text='Ex: Isolado Bacteriano, Plasmídeo, Fago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Posição física: Freezer, Rack, Caixa, Posição', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privada'), ('group', 'Grupo de pesquisa'), ('biobank', 'Biobank'), ('public', 'Pública')], default='private', max_length=20),
        ),
    ]
