# Generated by Django 5.2.8 on 2026-01-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='scientific_notes',
            field=models.TextField(blank=True, help_text='Caderno de Laboratório: Descrição de protocolos, anotações científicas e observações.', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='spectrometry_data',
            field=models.JSONField(blank=True, help_text='Coordenadas e dados brutos de espectrometria (ex: Scio/Infravermelho).', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações gerais e administrativas.', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Posição física detalhada: Prédio, Freezer, Gaveta, Caixa, Posição.', max_length=255, null=True),
        ),
    ]
