# Generated by Django 5.2.8 on 2026-02-03 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_molecularsequence_notebookentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebookentry',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='notebookentry',
            name='content',
        ),
        migrations.AlterField(
            model_name='notebookentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotebookBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Rich Text'), ('table', 'Data Table'), ('chart', 'Chart/Visualization'), ('code', 'Python Analysis')], default='text', max_length=20)),
                ('content_data', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.notebookentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='MolecularSequence',
        ),
    ]
