# Generated by Django 5.2.8 on 2026-02-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_molecularsequence_notebookentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biobank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='biobank',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='biobank',
            name='updated_at',
        ),
    ]
