# Generated by Django 4.2.28 on 2026-02-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_biobank_created_at_remove_biobank_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobank',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Grupo de pesquisa responsável pelo Biobanco', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biobanks', to='core.researchgroup'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privado (Apenas Dono)'), ('group', 'Grupo de Pesquisa'), ('biobank', 'Restrito ao Biobank (Interno)'), ('public', 'Público')], default='group', max_length=20),
        ),
    ]
