# Generated by Django 5.2.8 on 2026-02-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notebookentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='external_identifier',
            field=models.CharField(blank=True, help_text='ID, código de barras ou etiqueta original do biobanco parceiro/externo.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='parent_sample',
            field=models.ForeignKey(blank=True, help_text='Amostra original (pai) da qual esta alíquota ou derivado foi gerada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_samples', to='core.sample'),
        ),
    ]
