# Generated by Django 6.0.2 on 2026-02-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_biobank_research_group_alter_biobank_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='spectrometry_data',
        ),
    ]
