# Generated by Django 5.2.8 on 2026-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sample_external_identifier_sample_parent_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobank',
            name='biobank_type',
            field=models.CharField(choices=[('central', 'Biobanco Central (Hub Interno)'), ('partner', 'Biobanco Parceiro (Coletor/Afiliado)'), ('external', 'Instituição Externa (Origem Externa)')], default='central', help_text='Define o papel estrutural deste biobanco na rede.', max_length=20),
        ),
    ]
