# Generated by Django 5.2.8 on 2026-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_biobank_biobank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('freeze', 'Congelamento'), ('thaw', 'Descongelamento'), ('transfer', 'Transferência (Movimentação)'), ('qc_check', 'Controle de Qualidade'), ('external_receipt', 'Recebimento Externo (Parceiro)'), ('aliquoting', 'Aliquotagem (Geração de Filhos)'), ('derivation', 'Derivação / Processamento (Ex: Extração DNA/RNA)')], max_length=50),
        ),
    ]
