# Generated by Django 6.0.2 on 2026-02-16 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_sample_spectrometry_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Common name (e.g. Ethanol 70%)', max_length=255)),
                ('formula', models.CharField(blank=True, help_text='Molecular formula (e.g. C2H5OH)', max_length=100, null=True)),
                ('cas_number', models.CharField(blank=True, help_text='CAS Registry Number', max_length=50, null=True)),
                ('quantity', models.CharField(help_text='Quantity with units (e.g. 500mL, 10g)', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Shelf, Cabinet, or Fridge location', max_length=255, null=True)),
                ('msds_link', models.URLField(blank=True, help_text='Link to Material Safety Data Sheet', null=True)),
                ('hazard_notes', models.TextField(blank=True, help_text='Safety warnings (Flammable, Toxic, etc.)', null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('expired', 'Expired'), ('depleted', 'Depleted')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
