# Generated by Django 5.2.8 on 2026-02-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chemical'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='derivation_type',
            field=models.CharField(blank=True, help_text='Ex: Mutação, Passagem, Transformação com Plasmídeo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='parent_sample',
            field=models.ForeignKey(blank=True, help_text='Amostra de origem caso esta seja uma derivação/mutação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_samples', to='core.sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='visibility',
            field=models.CharField(choices=[('group', 'Grupo de pesquisa'), ('public', 'Pública')], default='group', max_length=20),
        ),
    ]
