# Generated by Django 5.2.8 on 2026-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sample_derivation_type_sample_parent_sample_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionuserrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectionuserrole',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionuserrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='members',
        ),
        migrations.RemoveField(
            model_name='biobank',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='visibility',
        ),
        migrations.AddField(
            model_name='biobank',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Marque para disponibilizar este biobanco publicamente'),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Marque para disponibilizar esta coleção publicamente'),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BiobankUserRole',
        ),
        migrations.DeleteModel(
            name='CollectionUserRole',
        ),
    ]
