# Generated by Django 5.2.8 on 2026-02-27 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_collectionuserrole_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.sample')),
                ('species', models.CharField(help_text='Nome científico. Ex: Escherichia coli', max_length=150)),
                ('strain', models.CharField(blank=True, help_text='Linhagem (Ex: BL21, MG1655)', max_length=100, null=True)),
                ('genotype', models.TextField(blank=True, help_text='Marcadores genéticos', null=True)),
                ('resistance_markers', models.JSONField(blank=True, default=list, help_text='Lista de antibióticos de resistência')),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bacteria',
                'verbose_name_plural': 'Bacteria',
            },
            bases=('core.sample',),
        ),
        migrations.CreateModel(
            name='Phage',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.sample')),
                ('morphotype', models.CharField(blank=True, choices=[('myovirus', 'Myovirus'), ('siphovirus', 'Siphovirus'), ('podovirus', 'Podovirus'), ('outros', 'Outros')], max_length=50, null=True)),
                ('taxonomy', models.CharField(blank=True, help_text='Ex: Autographiviridae, Straboviridae', max_length=100, null=True)),
                ('lifestyle', models.CharField(blank=True, choices=[('lytic', 'Lytic'), ('lysogenic', 'Lysogenic')], max_length=50, null=True)),
                ('isolation_source', models.CharField(blank=True, help_text='Ex: Esgoto, solo, amostra clínica', max_length=255, null=True)),
                ('genome_type', models.CharField(blank=True, choices=[('dsDNA', 'dsDNA'), ('ssDNA', 'ssDNA'), ('dsRNA', 'dsRNA'), ('ssRNA', 'ssRNA')], max_length=20, null=True)),
                ('genome_size_bp', models.PositiveIntegerField(blank=True, help_text='Tamanho em pares de bases', null=True)),
                ('ncbi_accession', models.CharField(blank=True, help_text='Link/ID do GenBank', max_length=100, null=True)),
                ('temp_C', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura ideal de crescimento', max_digits=4, null=True)),
                ('morphology_img', models.ImageField(blank=True, null=True, upload_to='phage_img/')),
                ('genome_sequence', models.FileField(blank=True, null=True, upload_to='phage_genomes/')),
            ],
            options={
                'verbose_name': 'Phage',
            },
            bases=('core.sample',),
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.sample')),
                ('name_official', models.CharField(help_text='Ex: pET28a(+)', max_length=100)),
                ('aliases', models.TextField(blank=True, help_text='Nomes alternativos ou apelidos', null=True)),
                ('vector_type', models.CharField(blank=True, choices=[('expression', 'Expression'), ('suicide', 'Suicide'), ('conjugation', 'Conjugation'), ('cloning', 'Cloning')], max_length=50, null=True)),
                ('resistance_markers', models.JSONField(blank=True, default=list)),
                ('induction_system', models.CharField(blank=True, help_text='Ex: T7, lac, araBAD', max_length=100, null=True)),
                ('vector_size_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('default_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vectors', to='core.bacteria')),
            ],
            options={
                'verbose_name': 'Vector',
            },
            bases=('core.sample',),
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.sample')),
                ('construction_name', models.CharField(help_text='Ex: pET28a-GFP', max_length=150)),
                ('insert_name', models.CharField(blank=True, help_text='Nome do gene/peça inserida. Ex: eGFP', max_length=100, null=True)),
                ('insert_size_bp', models.PositiveIntegerField(default=0)),
                ('actual_resistances', models.JSONField(blank=True, default=list, help_text='Resistências da construção final')),
                ('map_file', models.FileField(blank=True, null=True, upload_to='construction_maps/')),
                ('sequence_file', models.FileField(blank=True, null=True, upload_to='construction_seqs/')),
                ('origin_lab', models.CharField(blank=True, max_length=150, null=True)),
                ('host_strain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_constructions', to='core.bacteria')),
                ('parent_vector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constructions', to='core.vector')),
            ],
            options={
                'verbose_name': 'Construction',
            },
            bases=('core.sample',),
        ),
        migrations.CreateModel(
            name='HostRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_isolation_host', models.BooleanField(default=False, help_text='Define se esta é a bactéria mãe do isolamento')),
                ('efficiency_eop', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('plaque_morphology', models.ImageField(blank=True, null=True, upload_to='plaque_images/')),
                ('bacteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phage_interactions', to='core.bacteria')),
                ('phage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_interactions', to='core.phage')),
            ],
            options={
                'verbose_name': 'Host Range Interaction',
                'unique_together': {('phage', 'bacteria')},
            },
        ),
    ]
