# Generated by Django 5.2.8 on 2026-02-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bacteria_phage_vector_construction_hostrange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='derivation_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='parent_sample',
        ),
    ]
