# Generated by Django 5.2.8 on 2026-03-02 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_sample_derivation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('derived_from', 'Derivada de (Passagem/Subcultura)'), ('mutated_from', 'Mutação de'), ('assembled_from', 'Montada a partir de (Vetor + Inserto)'), ('extracted_from', 'Extraída de (DNA/RNA)'), ('infects', 'Infecta (Host-Range)'), ('other', 'Outro Relacionamento')], default='derived_from', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Detalhes do protocolo ou método de derivação.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_sample', models.ForeignKey(help_text='A amostra de origem (Pai)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.sample')),
                ('target_sample', models.ForeignKey(help_text='A amostra de destino (Filho/Derivada)', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.sample')),
            ],
            options={
                'verbose_name': 'Relacionamento de Amostra',
                'verbose_name_plural': 'Relacionamentos de Amostras',
                'unique_together': {('source_sample', 'target_sample', 'relationship_type')},
            },
        ),
    ]
