# Generated by Django 5.2.8 on 2026-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_samplerelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerelationship',
            name='relationship_type',
            field=models.CharField(choices=[('aliquot', 'Alíquota (Cópia exata em outro tubo)'), ('passage', 'Passagem / Subcultivo / Repique'), ('mutated_from', 'Mutação / Modificação de'), ('assembled_from', 'Montada a partir de (Vetor + Inserto)'), ('extracted_from', 'Extraída de (DNA/RNA)'), ('infects', 'Infecta (Host-Range)'), ('other', 'Outro Relacionamento')], default='aliquot', max_length=50),
        ),
    ]
