# Generated by Django 5.2.8 on 2026-03-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_samplerelationship_relationship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='collection',
        ),
        migrations.AddField(
            model_name='sample',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='samples', to='core.collection'),
        ),
        migrations.AddField(
            model_name='sample',
            name='lineage',
            field=models.ManyToManyField(blank=True, related_name='derived_from_lineage', through='core.SampleRelationship', through_fields=('source_sample', 'target_sample'), to='core.sample'),
        ),
    ]
