# Generated by Django 5.2.8 on 2026-03-02 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_sample_collection_sample_collections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleStorageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do nível (Ex: Freezer 1)', max_length=150)),
                ('level_index', models.PositiveIntegerField(help_text='0 é o nível mais alto/principal')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_levels', to='core.sample')),
            ],
            options={
                'verbose_name': 'Nível de Armazenamento',
                'verbose_name_plural': 'Níveis de Armazenamento',
                'ordering': ['level_index'],
                'unique_together': {('sample', 'level_index')},
            },
        ),
    ]
