# Generated by Django 5.2.8 on 2026-03-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_samplestoragelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='biobank',
        ),
    ]
