# Generated by Django 5.2.8 on 2026-03-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_collection_biobank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='host_strain',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='map_file',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='sequence_file',
        ),
        migrations.RemoveField(
            model_name='phage',
            name='genome_sequence',
        ),
        migrations.RemoveField(
            model_name='phage',
            name='morphology_img',
        ),
        migrations.RemoveField(
            model_name='vector',
            name='default_host',
        ),
        migrations.AddField(
            model_name='construction',
            name='final_size_bp',
            field=models.PositiveIntegerField(blank=True, help_text='Calculado automaticamente', null=True),
        ),
    ]
