# Generated by Django 5.2.8 on 2026-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_construction_host_strain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacteria',
            name='genus',
            field=models.CharField(blank=True, help_text='Genus. Ex: Escherichia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='genus',
            field=models.CharField(blank=True, help_text='Genus. Ex: Tequatrovirus', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='genotype',
            field=models.TextField(blank=True, help_text='Genetic markers', null=True),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='resistance_markers',
            field=models.JSONField(blank=True, default=list, help_text='List of antibiotic resistance markers'),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='species',
            field=models.CharField(help_text='Scientific name. Ex: Escherichia coli', max_length=150),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='strain',
            field=models.CharField(blank=True, help_text='Strain (Ex: BL21, MG1655)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='actual_resistances',
            field=models.JSONField(blank=True, default=list, help_text='Resistances of the final construction'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='final_size_bp',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated automatically', null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='insert_name',
            field=models.CharField(blank=True, help_text='Name of the inserted gene/part. Ex: eGFP', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostrange',
            name='is_isolation_host',
            field=models.BooleanField(default=False, help_text='Defines if this is the isolation host bacteria'),
        ),
        migrations.AlterField(
            model_name='phage',
            name='genome_size_bp',
            field=models.PositiveIntegerField(blank=True, help_text='Size in base pairs (bp)', null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='isolation_source',
            field=models.CharField(blank=True, help_text='Ex: Sewage, soil, clinical sample', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='morphotype',
            field=models.CharField(blank=True, choices=[('myovirus', 'Myovirus'), ('siphovirus', 'Siphovirus'), ('podovirus', 'Podovirus'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='ncbi_accession',
            field=models.CharField(blank=True, help_text='GenBank Link/ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='temp_C',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Optimal growth temperature', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='aliases',
            field=models.TextField(blank=True, help_text='Alternative names or aliases', null=True),
        ),
    ]
