# Generated by Django 5.2.8 on 2026-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bacteria_genus_phage_genus_alter_bacteria_genotype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefile',
            name='category',
            field=models.CharField(choices=[('image', 'Image (Microscopy/Gel)'), ('table', 'Table (CSV/Excel)'), ('sequence', 'Sequence (FASTA/FASTQ)'), ('pdf', 'PDF Document'), ('raw', 'Raw Data / Other')], default='raw', max_length=20),
        ),
    ]
