# Generated by Django 4.2.29 on 2026-03-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_event_event_type'),
        ('core', '0026_alter_samplefile_category'),
    ]

    operations = [
    ]
