# Generated by Django 4.2.29 on 2026-03-06 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_merge_20260304_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seq_type', models.CharField(choices=[('DNA', 'Sequência DNA (FASTA)'), ('PROTEIN', 'Proteína (FASTA)'), ('PDB', 'Estrutura 3D (PDB)')], default='PDB', max_length=10)),
                ('sequence_data', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Molecular Sequence',
            },
        ),
        migrations.AlterModelOptions(
            name='notebookentry',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Notebook Entry', 'verbose_name_plural': 'Notebook Entries'},
        ),
        migrations.RemoveField(
            model_name='biobank',
            name='biobank_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='external_identifier',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='parent_sample',
        ),
        migrations.AddField(
            model_name='notebookentry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('freeze', 'Congelamento'), ('thaw', 'Descongelamento'), ('transfer', 'Transferência (Movimentação)'), ('qc_check', 'Controle de Qualidade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notebookentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_notebook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NotebookBlock',
        ),
    ]
