# Generated by Django 4.2.29 on 2026-03-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_molecularsequence_alter_notebookentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.sample')),
                ('insert_name', models.CharField(help_text='Name of the inserted gene/part. Ex: eGFP', max_length=100)),
                ('insert_size_bp', models.PositiveIntegerField(default=0)),
                ('sequence', models.TextField(blank=True, help_text='FASTA or raw sequence', null=True)),
            ],
            options={
                'verbose_name': 'Insert',
            },
            bases=('core.sample',),
        ),
        migrations.CreateModel(
            name='Plasmid',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.sample')),
                ('construction_name', models.CharField(blank=True, help_text='Ex: pET28a-GFP. Leave empty to auto-fill with Backbone name if no insert.', max_length=150, null=True)),
                ('actual_resistances', models.JSONField(blank=True, default=list, help_text='Resistances of the final construction')),
                ('origin_lab', models.CharField(blank=True, max_length=150, null=True)),
                ('final_size_bp', models.PositiveIntegerField(blank=True, help_text='Calculated automatically', null=True)),
            ],
            options={
                'verbose_name': 'Plasmid (Backbone + Insert)',
            },
            bases=('core.sample',),
        ),
        # 1º: Primeiro renomeamos o modelo
        migrations.RenameModel(
            old_name='Vector',
            new_name='VectorBackbone',
        ),
        # 2º: Depois alteramos as opções do modelo já renomeado
        migrations.AlterModelOptions(
            name='vectorbackbone',
            options={'verbose_name': 'Vector Backbone'},
        ),
        migrations.DeleteModel(
            name='Construction',
        ),
        migrations.AddField(
            model_name='plasmid',
            name='backbone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plasmids', to='core.vectorbackbone'),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='insert_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plasmids', to='core.insert'),
        ),
    ]
