# Generated by Django 6.0.3 on 2026-03-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_insert_plasmid_alter_vectorbackbone_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasmid',
            name='insert_part',
        ),
        migrations.RemoveField(
            model_name='vectorbackbone',
            name='sample_ptr',
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='backbone',
        ),
        migrations.AlterModelOptions(
            name='plasmid',
            options={'verbose_name': 'Plasmid'},
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='actual_resistances',
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='final_size_bp',
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='origin_lab',
        ),
        migrations.AddField(
            model_name='bacteria',
            name='aliases',
            field=models.TextField(blank=True, help_text='Alternative names or common aliases', null=True),
        ),
        migrations.AddField(
            model_name='bacteria',
            name='isolation_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bacteria',
            name='official_name',
            field=models.CharField(blank=True, help_text='Official/Standard Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hostrange',
            name='notes',
            field=models.TextField(blank=True, help_text='Specific details about this infection/interaction', null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='aliases',
            field=models.TextField(blank=True, help_text='Alternative names or common aliases', null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='isolation_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='official_name',
            field=models.CharField(blank=True, help_text='Official/Standard Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='phage_name',
            field=models.CharField(blank=True, help_text='Phage Name. Ex: T4', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='backbone_aliases',
            field=models.TextField(blank=True, help_text='Alternative names', null=True),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='backbone_name',
            field=models.CharField(default='Unknown', help_text='Ex: pET28a(+)', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plasmid',
            name='backbone_resistance_markers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='backbone_size_bp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='induction_system',
            field=models.CharField(blank=True, help_text='Ex: T7, lac, araBAD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='insert_name',
            field=models.CharField(blank=True, help_text='Ex: eGFP', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='insert_resistance_markers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='insert_size_bp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='is_empty_vector',
            field=models.BooleanField(default=True, help_text='Is this circulating as an empty backbone?'),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='origin_of_replication',
            field=models.CharField(blank=True, help_text='Ex: pBR322, pUC', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose / Function of the insert', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='total_size_bp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='vector_type',
            field=models.CharField(blank=True, choices=[('expression', 'Expression'), ('suicide', 'Suicide'), ('conjugation', 'Conjugation'), ('cloning', 'Cloning')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='construction_name',
            field=models.CharField(blank=True, help_text='Ex: pET28a-GFP', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Insert',
        ),
        migrations.DeleteModel(
            name='VectorBackbone',
        ),
    ]
