# Generated by Django 6.0.3 on 2026-04-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_plasmid_insert_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Grupo de Pesquisa ao qual esta coleção pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='core.researchgroup'),
        ),
    ]
