# Generated by Django 6.0.3 on 2026-04-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_collection_research_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Grupo de Pesquisa (Laboratório) ao qual esta amostra pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='core.researchgroup'),
        ),
    ]
