# Generated by Django 6.0.3 on 2026-05-18 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_sample_research_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='sample_imports/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('partially_used', 'Partially used'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample import batch',
                'verbose_name_plural': 'Sample import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleIntakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('imported_sample_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('biobank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('research_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('scientific_notes', models.TextField(blank=True, null=True)),
                ('intake_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_biobank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_biobank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_arrival_date', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('movement_notes', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('waiting_review', 'Waiting review'), ('ready_to_fill', 'Ready to fill form'), ('used_for_sample', 'Used for sample'), ('rejected', 'Rejected')], default='waiting_review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.sampleimportbatch')),
                ('matched_biobank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_intake_records', to='core.biobank')),
                ('matched_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_intake_records', to='core.collection')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_records', to='core.sample')),
            ],
            options={
                'verbose_name': 'Sample intake record',
                'verbose_name_plural': 'Sample intake records',
                'ordering': ['batch', 'row_number'],
                'unique_together': {('batch', 'row_number')},
            },
        ),
    ]
