# Generated by Django 6.0.3 on 2026-05-19 15:03

import core.models.shipments.shipment
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_sampleimportbatch_sampleintakerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shipment_code', models.CharField(blank=True, max_length=64, unique=True)),
                ('flow_type', models.CharField(choices=[('incoming_receipt', 'Incoming receipt'), ('outgoing_shipment', 'Outgoing shipment'), ('internal_transfer', 'Internal transfer'), ('external_transfer', 'External transfer'), ('international_shipment', 'International shipment'), ('temporary_loan', 'Temporary loan'), ('return_to_origin', 'Return to origin'), ('disposal_transport', 'Disposal transport')], default='incoming_receipt', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('waiting_documents', 'Waiting documents'), ('waiting_authorization', 'Waiting authorization'), ('authorized', 'Authorized'), ('packing', 'Packing'), ('ready_for_dispatch', 'Ready for dispatch'), ('in_transit', 'In transit'), ('received_pending_qc', 'Received pending QC'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=40)),
                ('sender_institution', models.CharField(blank=True, max_length=255)),
                ('sender_responsible_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=100)),
                ('sender_address', models.TextField(blank=True)),
                ('recipient_institution', models.CharField(blank=True, max_length=255)),
                ('recipient_responsible_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=100)),
                ('recipient_address', models.TextField(blank=True)),
                ('transport_method', models.CharField(blank=True, max_length=100)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('tracking_code', models.CharField(blank=True, max_length=255)),
                ('temperature_condition', models.CharField(blank=True, max_length=100)),
                ('expected_dispatch_date', models.DateField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_shipments', to=settings.AUTH_USER_MODEL)),
                ('destination_biobank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_shipments', to='core.biobank')),
                ('origin_biobank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_shipments', to='core.biobank')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_shipments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('data', 'Required data'), ('document', 'Document'), ('authorization', 'Authorization'), ('packaging', 'Packaging'), ('label', 'Label'), ('dispatch', 'Dispatch'), ('receipt', 'Receipt')], max_length=40)),
                ('label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_shipment_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Shipment checklist item',
                'verbose_name_plural': 'Shipment checklist items',
                'ordering': ['checklist_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('classified', 'Classified'), ('document_generated', 'Document generated'), ('document_uploaded', 'Document uploaded'), ('authorized', 'Authorized'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('qc_checked', 'QC checked'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_events', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Shipment event',
                'verbose_name_plural': 'Shipment events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sample_id', models.CharField(blank=True, max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('sample_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('quantity_unit', models.CharField(blank=True, max_length=50)),
                ('container_count', models.PositiveIntegerField(default=1)),
                ('container_type', models.CharField(blank=True, max_length=100)),
                ('volume_or_weight', models.CharField(blank=True, max_length=100)),
                ('culture_medium', models.CharField(blank=True, max_length=255)),
                ('storage_condition', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('intake_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='core.sampleintakerecord')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='core.sample')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Shipment item',
                'verbose_name_plural': 'Shipment items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransportClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('bacteria', 'Bacteria'), ('phage', 'Phage'), ('plasmid', 'Plasmid'), ('mixed', 'Mixed'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('risk_class', models.CharField(choices=[('unknown', 'Unknown'), ('CR1', 'Risk class 1'), ('CR2', 'Risk class 2'), ('CR3', 'Risk class 3'), ('CR4', 'Risk class 4')], default='unknown', max_length=20)),
                ('biosafety_level', models.CharField(choices=[('unknown', 'Unknown'), ('NB1', 'NB-1'), ('NB2', 'NB-2'), ('NB3', 'NB-3'), ('NB4', 'NB-4')], default='unknown', max_length=20)),
                ('is_ogm', models.BooleanField(default=False)),
                ('is_genetic_heritage', models.BooleanField(default=False)),
                ('is_international', models.BooleanField(default=False)),
                ('is_category_b_un3373', models.BooleanField(default=False)),
                ('is_exempt_biological_material', models.BooleanField(default=False)),
                ('requires_cibio_notification', models.BooleanField(default=False)),
                ('requires_ctnbio_authorization', models.BooleanField(default=False)),
                ('requires_mta_ttm', models.BooleanField(default=False)),
                ('requires_sisgen', models.BooleanField(default=False)),
                ('requires_triple_packaging', models.BooleanField(default=False)),
                ('requires_biohazard_label', models.BooleanField(default=False)),
                ('requires_un3373_label', models.BooleanField(default=False)),
                ('requires_external_package_identification', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Transport classification',
                'verbose_name_plural': 'Transport classifications',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('content_declaration', 'Content declaration'), ('sender_declaration', 'Sender declaration'), ('external_package_identification', 'External package identification'), ('triple_packaging_checklist', 'Triple packaging checklist'), ('ogm_transport_notification', 'OGM transport notification'), ('mta_ttm', 'MTA/TTM'), ('shipment_invoice', 'Shipment invoice'), ('receipt_confirmation', 'Receipt confirmation'), ('other', 'Other')], max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('waiting_signature', 'Waiting signature'), ('signed', 'Signed'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=40)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to=core.models.shipments.shipment.shipment_document_upload_to)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to=core.models.shipments.shipment.shipment_document_upload_to)),
                ('generated_hash', models.CharField(blank=True, max_length=128)),
                ('signed_hash', models.CharField(blank=True, max_length=128)),
                ('requires_signature', models.BooleanField(default=False)),
                ('signature_provider', models.CharField(choices=[('manual_upload', 'Manual upload'), ('govbr_external', 'gov.br external signature'), ('usp_sam', 'USP SAM'), ('other', 'Other')], default='manual_upload', max_length=50)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.shipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_shipment_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment document',
                'verbose_name_plural': 'Shipment documents',
                'ordering': ['document_type', 'id'],
                'unique_together': {('shipment', 'document_type')},
            },
        ),
    ]
