# Generated by Django 6.0.3 on 2026-05-19 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_shipment_shipmentchecklistitem_shipmentevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_condition', models.CharField(choices=[('not_checked', 'Not checked'), ('intact', 'Intact'), ('damaged', 'Damaged'), ('leak_detected', 'Leak detected'), ('temperature_issue', 'Temperature issue'), ('missing_items', 'Missing items'), ('rejected', 'Rejected')], default='not_checked', max_length=40)),
                ('package_integrity_confirmed', models.BooleanField(default=False)),
                ('documents_received', models.BooleanField(default=False)),
                ('items_checked', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_intake_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_receipts', to='core.sampleimportbatch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_receipts', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Shipment receipt',
                'verbose_name_plural': 'Shipment receipts',
            },
        ),
    ]
