# Generated by Django 6.0.3 on 2026-05-19 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_shipmentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_type', models.CharField(choices=[('public_tracking', 'Public tracking'), ('public_edit', 'Public edit'), ('internal_scan', 'Internal scan')], default='public_tracking', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipment_access_tokens', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Shipment access token',
                'verbose_name_plural': 'Shipment access tokens',
                'indexes': [models.Index(fields=['token', 'access_type', 'is_active'], name='core_shipme_token_43d652_idx')],
            },
        ),
    ]
