# Generated by Django 6.0.3 on 2026-05-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_shipmentaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_full_name', models.CharField(max_length=255)),
                ('sender_document', models.CharField(blank=True, max_length=80)),
                ('sender_institution', models.CharField(max_length=255)),
                ('sender_address', models.TextField(blank=True)),
                ('sender_phone_email', models.CharField(blank=True, max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_institution', models.CharField(blank=True, max_length=255)),
                ('recipient_address', models.TextField(blank=True)),
                ('recipient_phone_email', models.CharField(blank=True, max_length=255)),
                ('material_type', models.CharField(blank=True, max_length=80)),
                ('risk_class', models.CharField(default='unknown', max_length=40)),
                ('biosafety_level', models.CharField(default='unknown', max_length=40)),
                ('is_ogm', models.BooleanField(default=False)),
                ('is_genetic_heritage', models.BooleanField(default=False)),
                ('is_international', models.BooleanField(default=False)),
                ('additional_description', models.TextField(blank=True)),
                ('content_description', models.TextField(blank=True)),
                ('quantity_volume', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(default='Pesquisa científica', max_length=255)),
                ('material_classification', models.CharField(choices=[('exempt_biological_material', 'Material biológico isento'), ('category_b_un3373', 'Substância biológica Categoria B - UN3373'), ('requires_review', 'Requer revisão do biobanco')], default='requires_review', max_length=80)),
                ('transport_conditions', models.TextField(blank=True)),
                ('confirms_no_prohibited_dangerous_goods', models.BooleanField(default=False)),
                ('confirms_no_leakage_or_contamination_risk', models.BooleanField(default=False)),
                ('confirms_transport_safety', models.BooleanField(default=False)),
                ('confirms_primary_container', models.BooleanField(default=False)),
                ('confirms_secondary_packaging', models.BooleanField(default=False)),
                ('confirms_absorbent_material', models.BooleanField(default=False)),
                ('confirms_rigid_outer_packaging', models.BooleanField(default=False)),
                ('confirms_triple_packaging', models.BooleanField(default=False)),
                ('confirms_sender_recipient_identification', models.BooleanField(default=False)),
                ('confirms_fragile_label', models.BooleanField(default=False)),
                ('confirms_biohazard_label', models.BooleanField(default=False)),
                ('confirms_un3373_label_when_applicable', models.BooleanField(default=False)),
                ('confirms_accompanying_documents', models.BooleanField(default=False)),
                ('accepts_sender_declaration', models.BooleanField(default=False)),
                ('accepts_content_declaration', models.BooleanField(default=False)),
                ('accepts_responsibility', models.BooleanField(default=False)),
                ('declaration_place', models.CharField(blank=True, max_length=255)),
                ('signer_name', models.CharField(blank=True, max_length=255)),
                ('signer_document', models.CharField(blank=True, max_length=80)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='core.shipment')),
            ],
            options={
                'verbose_name': 'Shipment declaration',
                'verbose_name_plural': 'Shipment declarations',
            },
        ),
    ]
