# Generated by Django 6.0.3 on 2026-05-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_shipmentdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(blank=True, choices=[('room', 'Room'), ('freezer', 'Freezer'), ('shelf', 'Shelf'), ('rack', 'Rack'), ('box', 'Box'), ('position', 'Position'), ('other', 'Other')], default='other', max_length=50)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.storagelocation')),
            ],
            options={
                'ordering': ['parent_id', 'rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SampleStorageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('container_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('moved', 'Moved'), ('depleted', 'Depleted')], default='active', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_assignments', to='core.sample')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_assignments', to='core.storagelocation')),
            ],
            options={
                'ordering': ['sample', 'rank', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_storage_location_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='samplestorageassignment',
            constraint=models.UniqueConstraint(fields=('sample', 'rank'), name='unique_sample_storage_assignment_rank'),
        ),
    ]
