# Generated by Django 6.0.3 on 2026-06-08 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_storagelocation_samplestorageassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDocumentFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('form_status', models.CharField(choices=[('required', 'Required'), ('form_saved', 'Form saved'), ('generated', 'Generated'), ('signed_uploaded', 'Signed uploaded'), ('under_review', 'Under review'), ('approved', 'Approved'), ('correction_requested', 'Correction requested')], default='required', max_length=40)),
                ('generated_html', models.TextField(blank=True)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='shipments/documents/signed/')),
                ('correction_note', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='core.shipmentdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shipment_document_forms', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_form_data', to='core.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipment_document_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shipment_id', 'document_type', 'id'],
            },
        ),
    ]
