# Generated by Django 6.0.3 on 2026-06-18 04:19

import core.models.lab_tools.notebook
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_shipment_document_form_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molecularsequence',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Molecular Sequence', 'verbose_name_plural': 'Molecular Sequences'},
        ),
        migrations.RemoveField(
            model_name='molecularsequence',
            name='author',
        ),
        migrations.RemoveField(
            model_name='molecularsequence',
            name='seq_type',
        ),
        migrations.RemoveField(
            model_name='molecularsequence',
            name='sequence_data',
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='features_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='gc_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='linked_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molecular_sequences', to='core.sample'),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molecular_sequences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='sequence_type',
            field=models.CharField(choices=[('dna', 'DNA'), ('rna', 'RNA'), ('protein', 'Protein'), ('plasmid', 'Plasmid'), ('primer', 'Primer'), ('insert', 'Insert'), ('other', 'Other')], default='dna', max_length=32),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='source_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molecular_sequences', to='core.notebookentry'),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='topology',
            field=models.CharField(choices=[('linear', 'Linear'), ('circular', 'Circular')], default='linear', max_length=32),
        ),
        migrations.AddField(
            model_name='molecularsequence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notebookentry',
            name='title',
            field=models.CharField(default='Untitled experiment', max_length=255),
        ),
        migrations.CreateModel(
            name='NotebookBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('table', 'Table'), ('code', 'Code / plot'), ('sequence', 'Sequence'), ('plasmid', 'Plasmid'), ('slurm_job', 'Slurm job'), ('attachment', 'Attachment')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.notebookentry')),
            ],
            options={
                'verbose_name': 'Notebook Block',
                'verbose_name_plural': 'Notebook Blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotebookAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.lab_tools.notebook.notebook_attachment_upload_to)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('table', 'Table'), ('result', 'Result'), ('sequence', 'Sequence'), ('other', 'Other')], default='other', max_length=32)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.notebookentry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.notebookblock')),
            ],
            options={
                'verbose_name': 'Notebook Attachment',
                'verbose_name_plural': 'Notebook Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotebookSlurmJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('partition', models.CharField(blank=True, max_length=64)),
                ('cpus', models.PositiveIntegerField(default=1)),
                ('memory', models.CharField(blank=True, max_length=32)),
                ('time_limit', models.CharField(blank=True, max_length=32)),
                ('command', models.TextField(blank=True)),
                ('workdir', models.CharField(blank=True, max_length=1024)),
                ('script_path', models.CharField(blank=True, max_length=1024)),
                ('stdout_path', models.CharField(blank=True, max_length=1024)),
                ('stderr_path', models.CharField(blank=True, max_length=1024)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slurm_jobs', to='core.notebookblock')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slurm_jobs', to='core.notebookentry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_slurm_jobs_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notebook Slurm Job',
                'verbose_name_plural': 'Notebook Slurm Jobs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotebookSampleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_links', to='core.notebookentry')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_sample_links_created', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_sample_links', to='core.sample')),
            ],
            options={
                'ordering': ['-linked_at'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'sample'), name='unique_notebook_entry_sample_link')],
            },
        ),
    ]
