# Generated by Django 6.0.3 on 2026-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_molecularsequence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookentry',
            name='entry_type',
            field=models.CharField(choices=[('experiment', 'Experiment'), ('protocol', 'Protocol'), ('analysis', 'Analysis'), ('inventory', 'Inventory'), ('meeting', 'Meeting / discussion'), ('other', 'Other')], default='experiment', max_length=32),
        ),
        migrations.AddField(
            model_name='notebookentry',
            name='experiment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookentry',
            name='project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notebookentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='notebookentry',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('lab', 'Lab'), ('shared', 'Shared')], default='private', max_length=32),
        ),
    ]
