# Generated by Django 6.0.3 on 2026-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_notebook_entry_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookentry',
            name='protocol_content',
            field=models.TextField(blank=True),
        ),
    ]
