# Generated by Django 6.0.3 on 2026-06-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_notebook_protocol_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookblock',
            name='block_type',
            field=models.CharField(choices=[('image', 'Image'), ('table', 'Table'), ('sequence', 'Sequence'), ('plasmid', 'Plasmid'), ('attachment', 'Attachment')], max_length=32),
        ),
        migrations.DeleteModel(
            name='NotebookSlurmJob',
        ),
    ]
