# Generated by Django 6.0.3 on 2026-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_notebook_code_slurm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookblock',
            name='block_type',
            field=models.CharField(choices=[('protocol', 'Protocol'), ('image', 'Image'), ('table', 'Table'), ('sequence', 'Sequence'), ('plasmid', 'Plasmid'), ('attachment', 'Attachment')], max_length=32),
        ),
    ]
