# Generated by Django 6.0.3 on 2026-07-01 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_notebook_protocol_block_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookChemicalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_chemical_links', to='core.chemical')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_links', to='core.notebookentry')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_chemical_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-linked_at'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'chemical'), name='unique_notebook_entry_chemical_link')],
            },
        ),
    ]
