# Generated by Django 6.0.3 on 2026-07-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_notebook_chemical_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feature_type', models.CharField(choices=[('promoter', 'Promoter'), ('rbs', 'RBS'), ('cds', 'CDS / ORF / Insert'), ('terminator', 'Terminator'), ('ori', 'Origin'), ('antibiotic', 'Antibiotic marker'), ('primer', 'Primer binding site'), ('domain', 'Protein domain'), ('utr', 'UTR'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('start', models.PositiveIntegerField(default=1)),
                ('end', models.PositiveIntegerField(default=1)),
                ('strand', models.CharField(choices=[('+', 'Forward'), ('-', 'Reverse'), ('.', 'Not applicable')], default='+', max_length=1)),
                ('color', models.CharField(default='#868e96', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('qualifiers_json', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.molecularsequence')),
            ],
            options={
                'ordering': ['order', 'start', 'id'],
            },
        ),
    ]
