# Generated by Django 6.0.3 on 2026-07-02 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_molecular_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biobank',
            name='description',
            field=models.TextField(blank=True, help_text='Institutional description of the biobank.', null=True),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this biobank is operational.'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Marks this biobank as visible in public or institutional catalogs.'),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='location_label',
            field=models.CharField(blank=True, help_text='Human-readable address or location label.', max_length=255),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='owner',
            field=models.ForeignKey(help_text='Primary biobank manager.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_biobanks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biobank',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Research group responsible for this biobank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biobanks', to='core.researchgroup'),
        ),
        migrations.CreateModel(
            name='BiobankUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('member', 'Member / legacy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biobank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.biobank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biobank_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biobank permission',
                'verbose_name_plural': 'Biobank permissions',
                'ordering': ['role', 'user__username'],
                'unique_together': {('user', 'biobank')},
            },
        ),
    ]
