# Generated by Django 6.0.3 on 2026-07-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_backfill_sample_research_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chemical',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Research group responsible for this reagent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemicals', to='core.researchgroup'),
        ),
    ]
