# Generated by Django 6.0.3 on 2026-07-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_chemical_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='catalog_number',
            field=models.CharField(blank=True, help_text='Supplier catalog number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Batch or lot number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='minimum_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='quantity_unit',
            field=models.CharField(blank=True, help_text='mL, L, g, mg, units, kits, bottles, etc.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='quantity_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Room, cabinet, freezer, shelf or box', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='storage_temperature',
            field=models.CharField(blank=True, help_text='-80C, -20C, 4C, RT, LN2, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier or manufacturer', max_length=255, null=True),
        ),
    ]
