# Generated by Django 6.0.3 on 2026-07-06 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_chemical_inventory_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('intake', 'Intake'), ('consumption', 'Consumption'), ('adjustment', 'Adjustment'), ('disposal', 'Disposal')], max_length=20)),
                ('amount_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('amount_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.chemical')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
