# Generated by Django 6.0.3 on 2026-07-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_chemical_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='biosafety_level',
            field=models.CharField(blank=True, choices=[('NB-1', 'NB-1'), ('NB-2', 'NB-2'), ('NB-3', 'NB-3'), ('NB-4', 'NB-4')], help_text='Biosafety level required for handling this sample.', max_length=10, null=True, verbose_name='Nível de biossegurança'),
        ),
    ]
