# Generated by Django 6.0.3 on 2026-07-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_sample_biosafety_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sender_cqb_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sender CQB code'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_group_researcher',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sender group / researcher'),
        ),
    ]
