# Generated by Django 6.0.3 on 2026-07-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_shipment_sender_cqb_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdocument',
            name='document_type',
            field=models.CharField(choices=[('content_declaration', 'Content declaration and traceability'), ('sender_declaration', 'Legacy ANTT sender declaration'), ('external_package_identification', 'External package identification'), ('triple_packaging_checklist', 'Triple packaging checklist'), ('ogm_transport_notification', 'OGM transport notification'), ('mta_ttm', 'MTA/TTM'), ('shipment_invoice', 'Shipment invoice'), ('receipt_confirmation', 'Receipt confirmation'), ('other', 'Other')], max_length=80),
        ),
    ]
