# Generated by Django 6.0.3 on 2026-07-16 01:45

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_chemical_files_and_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='keywordvalue',
            options={'ordering': ('keyword__name', 'value')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='keyword',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='keywordvalue',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='keywordvalue',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='core.keyword'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='core_keyword_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='keywordvalue',
            constraint=models.UniqueConstraint(models.F('keyword'), django.db.models.functions.text.Lower('value'), name='core_keyword_value_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='core_tag_name_ci_unique'),
        ),
    ]
