# Generated by Django 6.0.3 on 2026-07-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_secure_metadata_vocabularies'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='chemicals', to='core.keywordvalue'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='chemicals', to='core.tag'),
        ),
    ]
