# Generated by Django 6.0.3 on 2026-07-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_chemical_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecularsequence',
            name='features_json',
        ),
    ]
