# Generated by Django 6.0.3 on 2026-07-17 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_notebook_execution_partition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notebook_json', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='independent_notebook', to='core.notebookkerneldocument')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jupyter_notebooks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jupyter_notebooks_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jupyter Notebook',
                'verbose_name_plural': 'Jupyter Notebooks',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JupyterKernelSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=32)),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('running', 'Running'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], db_index=True, default='submitted', max_length=20)),
                ('partition', models.CharField(max_length=32)),
                ('cpus', models.PositiveSmallIntegerField(default=2)),
                ('memory_mb', models.PositiveIntegerField(default=8192)),
                ('time_minutes', models.PositiveIntegerField(default=60)),
                ('run_directory', models.CharField(max_length=1024)),
                ('kernel_info', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jupyter_kernel_sessions', to=settings.AUTH_USER_MODEL)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.jupyternotebook')),
            ],
            options={
                'verbose_name': 'Jupyter Kernel Session',
                'verbose_name_plural': 'Jupyter Kernel Sessions',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
