# Generated by Django 6.0.3 on 2026-08-08 17:50

import core.models.lab_tools.notebook
import core.services.lab_tools_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_use_user_home_for_eln_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, storage=core.services.lab_tools_storage.UserHomeLabToolsStorage(), upload_to=core.models.lab_tools.notebook.molecular_alignment_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_format', models.CharField(choices=[('aligned_fasta', 'Aligned FASTA'), ('clustal', 'CLUSTAL'), ('stockholm', 'Stockholm')], max_length=32)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('sequence_count', models.PositiveIntegerField(default=0)),
                ('alignment_length', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='core.molecularsequence')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molecular_alignments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Molecular Alignment',
                'verbose_name_plural': 'Molecular Alignments',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
