# Generated by Django 6.0.3 on 2026-08-08 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_add_molecular_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularSecondaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('structure', models.TextField()),
                ('source_format', models.CharField(choices=[('dot_bracket', 'Dot-bracket'), ('sequence_dot_bracket', 'Sequence + dot-bracket'), ('dbn', 'DBN'), ('rnafold', 'RNAfold-style text')], max_length=32)),
                ('source_text', models.TextField(blank=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('minimum_free_energy', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source_method', models.CharField(blank=True, max_length=255)),
                ('source_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molecular_secondary_structures_created', to=settings.AUTH_USER_MODEL)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_structures', to='core.molecularsequence')),
            ],
            options={
                'verbose_name': 'Molecular Secondary Structure',
                'verbose_name_plural': 'Molecular Secondary Structures',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['molecule', 'checksum_sha256'], name='core_molsec_mol_sha_idx')],
            },
        ),
    ]
