# Generated by Django 6.0.3 on 2026-08-14 19:34

import core.models.lab_tools.notebook
import core.services.lab_tools_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_add_molecular_secondary_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, storage=core.services.lab_tools_storage.UserHomeLabToolsStorage(), upload_to=core.models.lab_tools.notebook.molecular_structure_upload_to)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_format', models.CharField(choices=[('pdb', 'PDB'), ('mmcif', 'mmCIF')], max_length=32)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='core.molecularsequence')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molecular_structures_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Molecular Structure',
                'verbose_name_plural': 'Molecular Structures',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['molecule', 'checksum_sha256'], name='core_molstr_mol_sha_idx')],
            },
        ),
    ]
