# Generated by Django 6.0.3 on 2026-08-21 06:17

import core.models.samples.sample_files
import core.services.sample_data_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_add_shipment_recipient_group_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefile',
            name='file',
            field=models.FileField(max_length=512, storage=core.services.sample_data_storage.UserHomeSampleDataStorage(), upload_to=core.models.samples.sample_files.sample_file_upload_to),
        ),
    ]
