# Generated by Django 6.0.3 on 2026-08-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_use_user_home_for_sample_files'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='samplefile',
            constraint=models.CheckConstraint(condition=models.Q(('file__regex', '^users/[A-Za-z0-9][A-Za-z0-9_.-]{0,63}/samples/sample_[0-9]+_[A-Za-z0-9._-]+/files/[A-Za-z0-9][A-Za-z0-9_.-]{0,254}$')), name='samplefile_file_strict_user_path'),
        ),
    ]
