# Generated by Django 6.0.3 on 2026-08-21 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_enforce_samplefile_user_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplerelationship',
            options={'verbose_name': 'Sample Relationship', 'verbose_name_plural': 'Sample Relationships'},
        ),
        migrations.AlterModelOptions(
            name='samplestoragelevel',
            options={'ordering': ['level_index'], 'verbose_name': 'Storage Level', 'verbose_name_plural': 'Storage Levels'},
        ),
        migrations.AlterField(
            model_name='sample',
            name='biosafety_level',
            field=models.CharField(blank=True, choices=[('NB-1', 'NB-1'), ('NB-2', 'NB-2'), ('NB-3', 'NB-3'), ('NB-4', 'NB-4')], help_text='Biosafety level required for handling this sample.', max_length=10, null=True, verbose_name='Biosafety level'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Research group or laboratory associated with this sample.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='core.researchgroup'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Receipt'), ('qc', 'Quality Control'), ('available', 'Available / Approved'), ('rejected', 'Rejected / Nonviable'), ('depleted', 'Depleted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='samplerelationship',
            name='source_sample',
            field=models.ForeignKey(help_text='Source sample', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.sample'),
        ),
        migrations.AlterField(
            model_name='samplerelationship',
            name='target_sample',
            field=models.ForeignKey(help_text='Target or derived sample', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.sample'),
        ),
        migrations.AlterField(
            model_name='samplestoragelevel',
            name='level_index',
            field=models.PositiveIntegerField(help_text='Zero represents the root storage level'),
        ),
        migrations.AlterField(
            model_name='samplestoragelevel',
            name='name',
            field=models.CharField(help_text='Storage level name (for example, Freezer 1)', max_length=150),
        ),
    ]
