# Generated by Django 6.0.3 on 2026-08-21 08:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_normalize_sample_metadata_english'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='aliquot_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of physical aliquots represented by this Sample record.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sample',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_embargoed',
            field=models.BooleanField(default=False, help_text='Restricts public access while preserving authorized internal access.'),
        ),
        migrations.AddField(
            model_name='sample',
            name='purge_after',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Earliest time at which a Sample in Trash may be permanently deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether the Sample is part of the active inventory.'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allows public metadata access when the Sample is active and not embargoed.'),
        ),
        migrations.CreateModel(
            name='SampleDeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sample_pk', models.PositiveBigIntegerField(db_index=True)),
                ('original_sample_uuid', models.UUIDField(db_index=True)),
                ('original_sample_id', models.CharField(db_index=True, max_length=100)),
                ('original_sample_type', models.CharField(blank=True, max_length=100)),
                ('original_organism_name', models.CharField(blank=True, max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('storage_cleanup_errors', models.JSONField(blank=True, default=list)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_deletion_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Deletion Audit',
                'verbose_name_plural': 'Sample Deletion Audits',
                'ordering': ['-deleted_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SampleOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_site_name', models.CharField(blank=True, help_text='Human-readable name of the site where the material was collected.', max_length=255)),
                ('collection_date', models.DateField(blank=True, help_text='Date on which the source material was collected.', null=True)),
                ('geo_loc_name', models.CharField(blank=True, help_text='Geographic region, locality or water body associated with the collection site.', max_length=255, verbose_name='Geographic location')),
                ('country_or_ocean', models.CharField(blank=True, help_text='Country, territory, sea or ocean containing the collection site.', max_length=255, verbose_name='Country / Ocean')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 latitude in decimal degrees.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 longitude in decimal degrees.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('depth_m', models.DecimalField(blank=True, decimal_places=3, help_text='Depth below the local surface or water surface, in metres.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Depth (m)')),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=3, help_text='Elevation relative to mean sea level, in metres.', max_digits=12, null=True, verbose_name='Elevation / Altitude (m)')),
                ('habitat', models.CharField(blank=True, help_text='Concise description of the habitat at the collection site.', max_length=255)),
                ('environmental_medium', models.CharField(blank=True, help_text='Material or medium from which the Sample originated, for example ocean water, soil, sediment or host tissue.', max_length=255, verbose_name='Environmental medium')),
                ('env_broad_scale', models.CharField(blank=True, help_text='Broad environmental context compatible with MIxS-style provenance metadata.', max_length=255, verbose_name='Broad-scale environmental context')),
                ('env_local_scale', models.CharField(blank=True, help_text='Local environmental feature compatible with MIxS-style provenance metadata.', max_length=255, verbose_name='Local environmental context')),
                ('collection_method', models.TextField(blank=True, help_text='Method or protocol used to collect the source material.')),
                ('notes', models.TextField(blank=True, verbose_name='Origin notes')),
                ('location_visibility', models.CharField(choices=[('internal', 'Internal only'), ('approximate', 'Public - approximate'), ('exact', 'Public - exact')], default='internal', help_text='Controls whether geographic coordinates may later be exposed outside the authenticated internal interface.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='core.sample')),
            ],
            options={
                'verbose_name': 'Sample Origin',
                'verbose_name_plural': 'Sample Origins',
                'ordering': ['sample__sample_id'],
            },
        ),
    ]
