# Generated by Django 6.0.3 on 2026-08-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_sample_lifecycle_governance_and_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time. Leave blank for access without an expiration date.', null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_access_grants_created', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Access Grant',
                'verbose_name_plural': 'Sample Access Grants',
                'ordering': ['sample_id', 'user__username'],
                'indexes': [models.Index(fields=['user', 'access_level'], name='sample_access_user_level_idx'), models.Index(fields=['sample', 'expires_at'], name='sample_access_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('sample', 'user'), name='uniq_sample_access_grant_user')],
            },
        ),
    ]
