# Generated by Django 6.0.3 on 2026-08-21 17:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_sample_direct_access_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleorigin',
            name='acquisition_source',
            field=models.CharField(blank=True, choices=[('isolated_lab', 'Isolated by laboratory'), ('collaborator', 'Obtained from collaborator'), ('culture_collection', 'Obtained from culture collection'), ('external_repository', 'Obtained from external repository'), ('other', 'Other')], default='', help_text='How the biological material represented by this Sample was originally acquired.', max_length=40, verbose_name='Acquisition source'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='coordinate_source',
            field=models.CharField(blank=True, choices=[('map', 'Map selection'), ('gps', 'GPS'), ('gazetteer', 'Gazetteer / geocoding service'), ('provider', 'Reported by provider'), ('imported', 'Imported metadata'), ('other', 'Other')], default='', help_text='How the latitude / longitude pair was obtained.', max_length=30, verbose_name='Coordinate source'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='coordinate_uncertainty_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estimated horizontal uncertainty of the recorded coordinates in metres.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coordinate uncertainty (m)'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='culture_status',
            field=models.CharField(blank=True, choices=[('cultured', 'Cultured'), ('uncultured', 'Uncultured')], default='', help_text='Whether the source organism or material was maintained as a culture at the time represented by this provenance.', max_length=20, verbose_name='Culture status'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='ecosystem',
            field=models.CharField(blank=True, help_text='Highest-level ecosystem classification associated with the source environment.', max_length=255),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='ecosystem_category',
            field=models.CharField(blank=True, help_text='Second-level environmental classification.', max_length=255, verbose_name='Ecosystem category'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='ecosystem_subtype',
            field=models.CharField(blank=True, help_text='Environmental subtype within the selected ecosystem type.', max_length=255, verbose_name='Ecosystem subtype'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='ecosystem_type',
            field=models.CharField(blank=True, help_text='Environmental type within the selected ecosystem category.', max_length=255, verbose_name='Ecosystem type'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='source_collection_accession',
            field=models.CharField(blank=True, help_text='Accession, catalogue number or external identifier assigned by the source culture collection or repository.', max_length=255, verbose_name='Source collection accession'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='source_collection_name',
            field=models.CharField(blank=True, help_text='Name of an external culture collection, repository or provider from which the material was obtained.', max_length=255, verbose_name='Source culture collection'),
        ),
        migrations.AddField(
            model_name='sampleorigin',
            name='specific_ecosystem',
            field=models.CharField(blank=True, help_text='Most specific available environmental classification.', max_length=255, verbose_name='Specific ecosystem'),
        ),
    ]
