# Generated by Django 6.0.3 on 2026-08-22 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_phage_strain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleEnrichmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ncbi', 'NCBI'), ('bacdive', 'BacDive'), ('ictv', 'ICTV'), ('gtdb', 'GTDB')], max_length=32)),
                ('query', models.TextField()),
                ('request_url', models.TextField(blank=True)),
                ('source_version', models.CharField(blank=True, default='', max_length=64)),
                ('source_record_id', models.CharField(blank=True, default='', max_length=255)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_enrichment_snapshots_requested', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_snapshots', to='core.sample')),
            ],
            options={
                'verbose_name': 'Sample Enrichment Snapshot',
                'verbose_name_plural': 'Sample Enrichment Snapshots',
                'ordering': ['-fetched_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SampleExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ncbi', 'NCBI'), ('bacdive', 'BacDive'), ('ictv', 'ICTV'), ('gtdb', 'GTDB')], max_length=32)),
                ('identifier_type', models.CharField(max_length=64)),
                ('identifier', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='core.sample')),
            ],
            options={
                'verbose_name': 'Sample External Identifier',
                'verbose_name_plural': 'Sample External Identifiers',
                'ordering': ['source', 'identifier_type', '-is_primary', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='SampleTaxonomyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ncbi', 'NCBI'), ('bacdive', 'BacDive'), ('ictv', 'ICTV'), ('gtdb', 'GTDB')], max_length=32)),
                ('taxon_id', models.CharField(max_length=128)),
                ('scientific_name', models.CharField(max_length=255)),
                ('rank', models.CharField(blank=True, default='', max_length=64)),
                ('domain_or_realm', models.CharField(blank=True, default='', max_length=255)),
                ('kingdom', models.CharField(blank=True, default='', max_length=255)),
                ('phylum', models.CharField(blank=True, default='', max_length=255)),
                ('class_name', models.CharField(blank=True, default='', max_length=255)),
                ('order_name', models.CharField(blank=True, default='', max_length=255)),
                ('family', models.CharField(blank=True, default='', max_length=255)),
                ('genus', models.CharField(blank=True, default='', max_length=255)),
                ('species', models.CharField(blank=True, default='', max_length=255)),
                ('lineage', models.JSONField(blank=True, default=dict)),
                ('match_status', models.CharField(choices=[('candidate', 'Candidate'), ('verified', 'Verified'), ('conflict', 'Conflict'), ('unresolved', 'Unresolved'), ('stale', 'Stale')], default='candidate', max_length=16)),
                ('source_release', models.CharField(blank=True, default='', max_length=128)),
                ('is_current', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_taxonomy_assignments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_assignments', to='core.sample')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_assignments', to='core.sampleenrichmentsnapshot')),
            ],
            options={
                'verbose_name': 'Sample Taxonomy Assignment',
                'verbose_name_plural': 'Sample Taxonomy Assignments',
                'ordering': ['source', '-is_current', 'scientific_name'],
            },
        ),
        migrations.AddIndex(
            model_name='sampleenrichmentsnapshot',
            index=models.Index(fields=['sample', 'source', 'fetched_at'], name='samp_enrich_src_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleexternalidentifier',
            index=models.Index(fields=['sample', 'source', 'identifier_type'], name='samp_ext_src_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='sampleexternalidentifier',
            constraint=models.UniqueConstraint(fields=('sample', 'source', 'identifier_type', 'identifier'), name='uniq_sample_ext_identifier'),
        ),
        migrations.AddIndex(
            model_name='sampletaxonomyassignment',
            index=models.Index(fields=['sample', 'source', 'is_current'], name='samp_tax_src_curr_idx'),
        ),
        migrations.AddConstraint(
            model_name='sampletaxonomyassignment',
            constraint=models.UniqueConstraint(fields=('sample', 'source', 'taxon_id'), name='uniq_sample_tax_source_taxon'),
        ),
    ]
