# Generated by Django 6.0.3 on 2026-08-22 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_sample_external_enrichment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTaxonomyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('candidate', 'Candidate'), ('verified', 'Verified'), ('conflict', 'Conflict'), ('unresolved', 'Unresolved'), ('stale', 'Stale')], max_length=16)),
                ('new_status', models.CharField(choices=[('candidate', 'Candidate'), ('verified', 'Verified'), ('conflict', 'Conflict'), ('unresolved', 'Unresolved'), ('stale', 'Stale')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.sampletaxonomyassignment')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_taxonomy_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Taxonomy Review',
                'verbose_name_plural': 'Sample Taxonomy Reviews',
                'ordering': ['-reviewed_at', '-pk'],
                'indexes': [models.Index(fields=['assignment', 'reviewed_at'], name='samp_tax_review_time_idx')],
            },
        ),
    ]
