# Generated by Django 6.0.3 on 2026-08-22 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_sample_taxonomy_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGenomeAssemblyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ncbi', 'NCBI'), ('bacdive', 'BacDive'), ('ictv', 'ICTV'), ('gtdb', 'GTDB')], max_length=32)),
                ('accession', models.CharField(max_length=64)),
                ('current_accession', models.CharField(blank=True, default='', max_length=64)),
                ('paired_accession', models.CharField(blank=True, default='', max_length=64)),
                ('source_database', models.CharField(blank=True, default='', max_length=64)),
                ('organism_name', models.CharField(blank=True, default='', max_length=255)),
                ('taxon_id', models.CharField(blank=True, default='', max_length=128)),
                ('assembly_name', models.CharField(blank=True, default='', max_length=255)),
                ('assembly_level', models.CharField(blank=True, default='', max_length=128)),
                ('assembly_status', models.CharField(blank=True, default='', max_length=64)),
                ('assembly_type', models.CharField(blank=True, default='', max_length=128)),
                ('refseq_category', models.CharField(blank=True, default='', max_length=128)),
                ('release_date', models.CharField(blank=True, default='', max_length=32)),
                ('submitter', models.CharField(blank=True, default='', max_length=255)),
                ('bioproject_accession', models.CharField(blank=True, default='', max_length=64)),
                ('biosample_accession', models.CharField(blank=True, default='', max_length=64)),
                ('total_sequence_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('number_of_contigs', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_scaffolds', models.PositiveIntegerField(blank=True, null=True)),
                ('contig_n50', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scaffold_n50', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gc_percent', models.FloatField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('candidate', 'Candidate'), ('verified', 'Verified'), ('conflict', 'Conflict'), ('unresolved', 'Unresolved'), ('stale', 'Stale')], default='candidate', max_length=16)),
                ('is_current', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_genome_assembly_assignments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_assembly_assignments', to='core.sample')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genome_assembly_assignments', to='core.sampleenrichmentsnapshot')),
            ],
            options={
                'verbose_name': 'Sample Genome Assembly Assignment',
                'verbose_name_plural': 'Sample Genome Assembly Assignments',
                'ordering': ['source', '-is_current', 'accession'],
            },
        ),
        migrations.CreateModel(
            name='SampleGenomeAssemblyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('candidate', 'Candidate'), ('verified', 'Verified'), ('conflict', 'Conflict'), ('unresolved', 'Unresolved'), ('stale', 'Stale')], max_length=16)),
                ('new_status', models.CharField(choices=[('candidate', 'Candidate'), ('verified', 'Verified'), ('conflict', 'Conflict'), ('unresolved', 'Unresolved'), ('stale', 'Stale')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.samplegenomeassemblyassignment')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_genome_assembly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Genome Assembly Review',
                'verbose_name_plural': 'Sample Genome Assembly Reviews',
                'ordering': ['-reviewed_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='samplegenomeassemblyassignment',
            index=models.Index(fields=['sample', 'source', 'is_current'], name='samp_asm_src_curr_idx'),
        ),
        migrations.AddConstraint(
            model_name='samplegenomeassemblyassignment',
            constraint=models.UniqueConstraint(fields=('sample', 'source', 'accession'), name='uniq_sample_asm_src_acc'),
        ),
        migrations.AddIndex(
            model_name='samplegenomeassemblyreview',
            index=models.Index(fields=['assignment', 'reviewed_at'], name='samp_asm_review_time_idx'),
        ),
    ]
