# Generated by Django 6.0.3 on 2026-08-23 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_sample_genome_assembly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='department or laboratory')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('expertise', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('profile_visibility', models.CharField(choices=[('private', 'Private'), ('members', 'Authenticated members'), ('public', 'Public')], default='members', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
