# Generated by Django 6.0.3 on 2026-08-24 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0082_add_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('access_level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('manage', 'Manage')], default='view', max_length=12)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_access_grants_created', to=settings.AUTH_USER_MODEL)),
                ('research_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_grants', to='core.researchgroup')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_access_grants_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('content_type_id', 'object_id', 'id'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_resgrant_target_idx'), models.Index(fields=['expires_at', 'revoked_at'], name='core_resgrant_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('research_group__isnull', True), ('user__isnull', False)), models.Q(('research_group__isnull', False), ('user__isnull', True)), _connector='OR'), name='resource_grant_one_principal'), models.CheckConstraint(condition=models.Q(('access_level__in', ('view', 'edit', 'manage'))), name='resource_grant_valid_access'), models.CheckConstraint(condition=models.Q(('revoked_by__isnull', True), ('revoked_at__isnull', False), _connector='OR'), name='resource_grant_revoker_time'), models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('user__isnull', False)), fields=('content_type', 'object_id', 'user'), name='resource_grant_active_user_uniq'), models.UniqueConstraint(condition=models.Q(('research_group__isnull', False), ('revoked_at__isnull', True)), fields=('content_type', 'object_id', 'research_group'), name='resource_grant_active_group_uniq')],
            },
        ),
    ]
