# Generated by Django 6.0.3 on 2026-08-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_add_resource_access_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerelationship',
            name='notes',
            field=models.TextField(blank=True, help_text='Protocol or derivation method details.', null=True),
        ),
        migrations.AlterField(
            model_name='samplerelationship',
            name='relationship_type',
            field=models.CharField(choices=[('aliquot', 'Aliquot (exact copy in another tube)'), ('passage', 'Passage / Subculture'), ('mutated_from', 'Mutation / Modification of'), ('assembled_from', 'Assembled from (Vector + Insert)'), ('extracted_from', 'Extracted from (DNA/RNA)'), ('infects', 'Infects (Host Range)'), ('other', 'Other Relationship')], default='aliquot', max_length=50),
        ),
    ]
