# Generated by Django 6.0.3 on 2026-08-28 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_normalize_sample_relationship_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='Indica se a Collection está ativa para novos cadastros'),
        ),
        migrations.CreateModel(
            name='CollectionLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('deactivated', 'Deactivated'), ('reactivated', 'Reactivated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='core.collection')),
            ],
            options={
                'verbose_name': 'Collection lifecycle event',
                'verbose_name_plural': 'Collection lifecycle events',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
