from core.services.shipment_requirements_engine import evaluate_shipment_requirements
from core.services.shipment_document_generator import get_initial_values_from_shipment, render_document_html
from core.services.shipment_document_form_schemas import get_document_form_schema, extract_form_values
from core.models import ShipmentDocument, ShipmentDocumentFormData, ShipmentChecklistItem
from django.http import HttpResponse
try:
    from core.models import ShipmentDocument
except ImportError:
    from core.models.shipments.shipment import ShipmentDocument

import hashlib
from core.models import Shipment, TransportClassification, ShipmentEvent
from core.shipment_forms import ShipmentSetupForm, ShipmentItemSetupForm, TransportClassificationSetupForm
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.db.models import Q, Count

from core.context import base_context
from core.models import Shipment
from core.services.shipment_workflow import sync_shipment_requirements
from core.services.shipment_qr import build_internal_shipment_scan_url, build_qr_data_uri
from core.services.shipment_receipt import mark_shipment_received, create_intake_records_from_shipment
from core.permissions.shipments import visible_shipments_for_user


@login_required
def shipments_list_view(request):
    shipments = (
        visible_shipments_for_user(request.user)
        .select_related("origin_biobank", "destination_biobank", "requested_by")
        .prefetch_related("items", "documents", "checklist_items")
        .all()
    )

    q = request.GET.get("q", "").strip()
    status = request.GET.get("status", "").strip()
    flow_type = request.GET.get("flow_type", "").strip()

    if q:
        shipments = shipments.filter(
            Q(shipment_code__icontains=q)
            | Q(sender_institution__icontains=q)
            | Q(recipient_institution__icontains=q)
            | Q(tracking_code__icontains=q)
            | Q(items__imported_sample_id__icontains=q)
            | Q(items__material_name__icontains=q)
        ).distinct()

    if status:
        shipments = shipments.filter(status=status)

    if flow_type:
        shipments = shipments.filter(flow_type=flow_type)

    ctx = base_context(request)
    ctx.update({
        "shipments": shipments,
        "status_choices": Shipment.STATUS_CHOICES,
        "flow_type_choices": Shipment.FLOW_TYPES,
        "selected_status": status,
        "selected_flow_type": flow_type,
        "query": q,
    })

    return render(request, "internal/shipments/list.html", ctx)


def _safe_label(value):
    if value is None:
        return ""
    return str(value).strip()




SHIPMENT_DOCUMENT_LABELS = {
    "content_declaration": "Content declaration and traceability",
    "sender_declaration": "Legacy ANTT sender declaration",
    "external_package_identification": "External package identification",
    "triple_packaging_checklist": "Triple packaging checklist",
    "ogm_transport_notification": "OGM transport notification",
    "mta_ttm": "MTA/TTM",
    "shipment_invoice": "Shipment invoice",
    "receipt_confirmation": "Receipt confirmation",
}

CHECKLIST_TYPE_LABELS = {
    "data": "Required data",
    "document": "Document",
    "packaging": "Packaging",
    "label": "Label",
    "authorization": "Authorization",
}


def _choice_label(obj, field_name, fallback_map=None):
    raw_value = getattr(obj, field_name, "")

    if raw_value is None:
        return ""

    raw_text = str(raw_value).strip()

    if fallback_map and raw_text in fallback_map:
        return fallback_map[raw_text]

    try:
        field = obj._meta.get_field(field_name)
        choices = dict(getattr(field, "flatchoices", None) or field.choices or [])
        return str(choices.get(raw_value, choices.get(raw_text, raw_text)))
    except Exception:
        return raw_text


def _shipment_document_label(document):
    return _choice_label(
        document,
        "document_type",
        fallback_map=SHIPMENT_DOCUMENT_LABELS,
    )


def _shipment_document_status_label(document):
    return _choice_label(document, "status")


def _build_shipment_review_actions(shipment, checklist_items, documents):
    """
    Convert passive checklist rows into actionable review tasks.

    The checklist is generated by sync_shipment_requirements(), but the
    detail page should point each pending item to the most useful screen:
    setup/edit, documents review, or package outputs.
    """
    document_labels = {}
    document_types = {}

    for document in documents:
        label = _shipment_document_label(document)
        document_labels[label.lower()] = document
        document_types[_safe_label(document.document_type).lower()] = document

    actions = []

    for item in checklist_items:
        checklist_type = _safe_label(getattr(item, "checklist_type", ""))
        label = _safe_label(getattr(item, "label", ""))
        label_lower = label.lower()

        action_label = "Review"
        action_url = ""
        action_kind = "secondary"

        if checklist_type == "data":
            action_label = "Edit shipment"
            action_url = reverse("shipment_edit", kwargs={"shipment_id": shipment.id})
            action_kind = "primary"

        elif checklist_type in ["document", "authorization"]:
            action_label = "Open documents"
            action_url = reverse("shipment_documents_review", kwargs={"shipment_id": shipment.id})
            action_kind = "warning"

        elif checklist_type in ["label", "packaging"]:
            action_label = "Open package outputs"
            action_url = reverse("shipment_package_labels", kwargs={"shipment_id": shipment.id})
            action_kind = "info"

        if "required document available:" in label_lower:
            doc_label = label_lower.split("required document available:", 1)[1].strip()
            document = document_labels.get(doc_label)

            if document is not None:
                action_label = f"Open {_shipment_document_label(document)}"
                action_url = reverse(
                    "shipment_document_workspace",
                    kwargs={
                        "shipment_id": shipment.id,
                        "document_id": document.id,
                    },
                )
                action_kind = "warning"

        actions.append({
            "id": item.id,
            "label": label,
            "type": checklist_type,
            "type_label": _choice_label(item, "checklist_type", CHECKLIST_TYPE_LABELS),
            "is_completed": item.is_completed,
            "is_required": item.is_required,
            "action_label": action_label,
            "action_url": action_url,
            "action_kind": action_kind,
        })

    return actions


@login_required
def shipment_detail_view(request, shipment_id):
    shipment = get_object_or_404(
        visible_shipments_for_user(request.user)
        .select_related(
            "origin_biobank",
            "destination_biobank",
            "requested_by",
            "reviewed_by",
            "authorized_by",
        )
        .prefetch_related(
            "items",
            "documents",
            "checklist_items",
            "events",
        ),
        id=shipment_id,
    )

    if request.method == "POST":
        action = request.POST.get("action")

        if action == "sync_requirements":
            result = sync_shipment_requirements(shipment, actor=request.user)
            messages.success(request, result["message"])
            return redirect("shipment_detail", shipment_id=shipment.id)

        if action == "mark_received":
            mark_shipment_received(
                shipment,
                user=request.user,
                notes=request.POST.get("notes", ""),
            )
            messages.success(request, "Shipment marked as received and pending QC.")
            return redirect("shipment_detail", shipment_id=shipment.id)

        if action == "create_intake_records":
            result = create_intake_records_from_shipment(
                shipment,
                user=request.user,
            )

            if result.get("blocked"):
                messages.warning(request, result["message"])
                return redirect("shipment_detail", shipment_id=shipment.id)

            messages.success(
                request,
                f"Intake records generated. Created: {result['created']}. Skipped: {result['skipped']}."
            )
            return redirect("shipment_detail", shipment_id=shipment.id)

    items = list(shipment.items.all())
    documents = list(shipment.documents.all().order_by("document_type", "id"))
    document_rows = [
        {
            "document": document,
            "label": _shipment_document_label(document),
            "status_label": _shipment_document_status_label(document),
        }
        for document in documents
    ]
    checklist_items = list(shipment.checklist_items.all().order_by("is_completed", "checklist_type", "id"))
    events = list(shipment.events.all().order_by("-created_at", "-id"))

    review_actions = _build_shipment_review_actions(
        shipment=shipment,
        checklist_items=checklist_items,
        documents=documents,
    )

    pending_actions = [action for action in review_actions if not action["is_completed"]]
    completed_actions = [action for action in review_actions if action["is_completed"]]

    ctx = base_context(request)
    ctx.update({
        "shipment": shipment,
        "items": items,
        "documents": documents,
        "document_rows": document_rows,
        "checklist_items": checklist_items,
        "review_actions": review_actions,
        "pending_actions": pending_actions,
        "completed_actions": completed_actions,
        "events": events,
        "classification": getattr(shipment, "classification", None),
        "receipt": getattr(shipment, "receipt", None),
        "shipment_scan_url": build_internal_shipment_scan_url(request, shipment),
        "shipment_qr_data_uri": build_qr_data_uri(build_internal_shipment_scan_url(request, shipment)),
    })



    # Rebuild document rows from the active requirements engine.
    # This ensures the detail UI only shows documents required for the current
    # shipment classification: Risk Class, NB level and OGM status.
    requirement_snapshot = evaluate_shipment_requirements(shipment)
    required_documents = list(requirement_snapshot.get("documents", []))

    existing_documents = {
        document.document_type: document
        for document in shipment.documents.order_by("document_type", "id")
    }

    status_labels = {
        "required": "Required",
        "draft": "Required",
        "form_saved": "Form saved",
        "generated": "Generated",
        "signed_uploaded": "Signed uploaded",
        "uploaded": "Signed uploaded",
        "under_review": "Under review",
        "submitted": "Under review",
        "approved": "Approved",
        "correction_requested": "Correction requested",
        "rejected": "Correction requested",
    }

    status_badges = {
        "required": "bg-secondary",
        "draft": "bg-secondary",
        "form_saved": "bg-info text-dark",
        "generated": "bg-primary",
        "signed_uploaded": "bg-warning text-dark",
        "uploaded": "bg-warning text-dark",
        "under_review": "bg-info text-dark",
        "submitted": "bg-info text-dark",
        "approved": "bg-success",
        "correction_requested": "bg-danger",
        "rejected": "bg-danger",
    }

    rebuilt_document_rows = []

    for requirement in required_documents:
        document_type = getattr(requirement, "code", "")
        document = existing_documents.get(document_type)

        if document is None:
            continue

        label = (
            getattr(requirement, "label", "")
            or getattr(document, "title", "")
            or getattr(document, "label", "")
            or document.document_type.replace("_", " ").title()
        )

        requires_signature = bool(
            getattr(requirement, "requires_signature", getattr(document, "requires_signature", False))
        )

        raw_status = "required"
        form_status = ""
        form_data = None

        try:
            form_data = document.form_data
            form_status = getattr(form_data, "form_status", "") or ""
        except Exception:
            form_data = None

        if form_status:
            raw_status = form_status
        else:
            raw_status = getattr(document, "status", "") or "required"

        if raw_status == "draft":
            raw_status = "required"

        rebuilt_document_rows.append({
            "document": document,
            "label": label,
            "requires_signature": requires_signature,
            "status": raw_status,
            "status_label": status_labels.get(raw_status, raw_status.replace("_", " ").title()),
            "status_badge_class": status_badges.get(raw_status, "bg-secondary"),
            "form_status": form_status,
            "form_data": form_data,
        })

    ctx["document_rows"] = rebuilt_document_rows

    return render(request, "internal/shipments/detail.html", ctx)


@login_required
def shipment_scan_view(request, shipment_uuid):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), uuid=shipment_uuid)
    messages.info(request, f"Shipment {shipment.shipment_code} loaded from QR code.")
    return redirect("shipment_detail", shipment_id=shipment.id)

from core.services.shipment_document_gate import (
    approve_document_package,
    can_release_final_package_outputs,
    document_signed_file,
    get_pending_required_signed_documents,
)


@login_required
def shipment_approve_documents_view(request, shipment_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)

    if request.method != "POST":
        return redirect("shipment_detail", shipment_id=shipment.id)

    result = approve_document_package(shipment, actor=request.user)

    if result["approved"]:
        messages.success(
            request,
            "Required signed documents were approved. Final package labels and QR are now released.",
        )
    else:
        pending_names = ", ".join(
            document.get_document_type_display()
            for document in result["pending_documents"]
        )
        messages.error(
            request,
            f"Cannot approve yet. Pending signed documents: {pending_names}",
        )

    return redirect("shipment_detail", shipment_id=shipment.id)


@login_required
def shipment_package_labels_view(request, shipment_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)

    if not can_release_final_package_outputs(shipment):
        messages.error(
            request,
            "Final package labels are blocked until all required signed documents are uploaded and approved internally.",
        )
        return redirect("shipment_detail", shipment_id=shipment.id)

    access_token = shipment.access_tokens.filter(
        access_type="public_tracking",
        is_active=True,
    ).first()

    public_tracking_url = ""

    if access_token:
        public_tracking_url = request.build_absolute_uri(
            reverse("public_shipment_track", kwargs={"token": access_token.token})
        )

    package_qr_data_uri = build_qr_data_uri(
        public_tracking_url or shipment.shipment_code
    )

    classification = getattr(shipment, "classification", None)

    return render(
        request,
        "internal/shipments/package_labels.html",
        {
            "shipment": shipment,
            "items": shipment.items.all(),
            "classification": classification,
            "label_flags": _shipment_package_label_flags(classification),
            "public_tracking_url": public_tracking_url,
            "package_qr_data_uri": package_qr_data_uri,
            "pending_required_documents": get_pending_required_signed_documents(shipment),
        },
    )


@login_required
def shipment_documents_review_view(request, shipment_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)

    pending_required_documents = get_pending_required_signed_documents(shipment)
    can_release_outputs = can_release_final_package_outputs(shipment)

    return render(
        request,
        "internal/shipments/documents_review.html",
        {
            "shipment": shipment,
            "documents": shipment.documents.all().order_by("document_type", "id"),
            "pending_required_documents": pending_required_documents,
            "can_release_final_outputs": can_release_outputs,
        },
    )


@login_required
def shipment_request_document_correction_view(request, shipment_id, document_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)
    document = get_object_or_404(
        ShipmentDocument,
        id=document_id,
        shipment=shipment,
    )

    if request.method != "POST":
        return redirect("shipment_documents_review", shipment_id=shipment.id)

    correction_note = request.POST.get("correction_note", "").strip()

    # Keep status handling tolerant to the choices currently available in the model.
    status_field = ShipmentDocument._meta.get_field("status")
    available_statuses = [value for value, _label in status_field.choices]

    for candidate in ["correction_requested", "rejected", "waiting_documents", "draft"]:
        if candidate in available_statuses:
            document.status = candidate
            document.save(update_fields=["status"])
            break

    old_status = shipment.status
    shipment.status = "waiting_documents"
    shipment.updated_at = timezone.now()
    shipment.save(update_fields=["status", "updated_at"])

    ShipmentEvent.objects.create(
        shipment=shipment,
        event_type="updated",
        actor=request.user,
        notes=(
            f"Document correction requested: {document.get_document_type_display()}. "
            f"{correction_note or 'No additional correction note provided.'} "
            f"Status changed from {old_status} to waiting_documents."
        ),
    )

    messages.warning(
        request,
        f"Correction requested for {document.get_document_type_display()}. "
        "The shipment was moved back to waiting documents.",
    )

    return redirect("shipment_documents_review", shipment_id=shipment.id)


def _shipment_package_label_flags(classification):
    """
    Determine which external package labels must be printed.

    Rules:
    - Fragile label: always shown.
    - Biohazard label: OGM or classification requires biohazard label.
    - UN3373 label: risk class 2+ or biosafety level NB2+ or classification requires UN3373.
    - Restricted opening warning: shown for OGM, biohazard, UN3373, or triple packaging cases.
    """
    if classification is None:
        return {
            "show_fragile": True,
            "show_biohazard": False,
            "show_un3373": False,
            "show_restricted_opening": False,
            "show_triple_packaging_notice": False,
        }

    risk_class = (classification.risk_class or "").upper().replace("-", "")
    biosafety_level = (classification.biosafety_level or "").upper().replace("-", "")

    is_cr2_or_higher = risk_class in {"CR2", "CR3", "CR4"}
    is_nb2_or_higher = biosafety_level in {"NB2", "NB3", "NB4"}

    show_biohazard = bool(
        classification.is_ogm
        or getattr(classification, "requires_biohazard_label", False)
        or is_nb2_or_higher
    )

    show_un3373 = bool(
        getattr(classification, "requires_un3373_label", False)
        or is_cr2_or_higher
        or is_nb2_or_higher
    )

    show_triple_packaging_notice = bool(
        getattr(classification, "requires_triple_packaging", False)
        or show_un3373
        or show_biohazard
    )

    show_restricted_opening = bool(
        classification.is_ogm
        or show_biohazard
        or show_un3373
        or show_triple_packaging_notice
    )

    return {
        "show_fragile": True,
        "show_biohazard": show_biohazard,
        "show_un3373": show_un3373,
        "show_restricted_opening": show_restricted_opening,
        "show_triple_packaging_notice": show_triple_packaging_notice,
    }




def _normalize_boolean_post_data_for_model(post_data, model, prefix=None):
    """
    Convert empty BooleanField POST values into False.

    Supports both unprefixed names and prefixed ModelForm names:
    is_ogm and classification-is_ogm.
    """
    data = post_data.copy()

    for field in model._meta.fields:
        if field.get_internal_type() != "BooleanField":
            continue

        names = [field.name]

        if prefix:
            names.insert(0, f"{prefix}-{field.name}")

        for name in names:
            if name not in data or data.get(name) in ["", None]:
                data[name] = "false"

    return data

@login_required
def shipment_edit_view(request, shipment_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)
    item = shipment.items.order_by("id").first()

    classification, _ = TransportClassification.objects.get_or_create(
        shipment=shipment,
        defaults={
            "material_type": "unknown",
            "risk_class": "unknown",
            "biosafety_level": "unknown",
            "is_ogm": False,
            "is_genetic_heritage": False,
            "is_international": False,
        },
    )

    if request.method == "POST":
        shipment_form = ShipmentSetupForm(
            request.POST,
            instance=shipment,
            prefix="shipment",
        )
        item_form = ShipmentItemSetupForm(
            request.POST,
            instance=item,
            prefix="item",
        ) if item else None
        classification_form = TransportClassificationSetupForm(
            _normalize_boolean_post_data_for_model(
                request.POST,
                classification.__class__,
                prefix="classification",
            ),
            instance=classification,
            prefix="classification",
        )

        forms_valid = shipment_form.is_valid() and classification_form.is_valid()

        if item_form is not None:
            forms_valid = forms_valid and item_form.is_valid()

        if forms_valid:
            shipment = shipment_form.save()

            if item_form is not None:
                item_form.save()

            classification = classification_form.save()
            classification.apply_default_rules(save=True)

            ShipmentEvent.objects.create(
                shipment=shipment,
                event_type="updated",
                actor=request.user,
                notes="Shipment setup updated by internal user.",
            )

            result = sync_shipment_requirements(shipment, actor=request.user)

            if "sync_requirements" in request.POST:
                messages.success(
                    request,
                    result.get("message", "Shipment requirements synchronized."),
                )
            elif "continue_review" in request.POST:
                messages.success(
                    request,
                    "Shipment saved and requirements synchronized.",
                )
            else:
                messages.success(
                    request,
                    "Shipment draft saved and requirements synchronized.",
                )

            if "continue_review" in request.POST:
                return redirect("shipment_detail", shipment_id=shipment.id)

            return redirect("shipment_edit", shipment_id=shipment.id)

        messages.error(request, "Please review the shipment fields before continuing.")

    else:
        shipment_form = ShipmentSetupForm(instance=shipment, prefix="shipment")
        item_form = ShipmentItemSetupForm(instance=item, prefix="item") if item else None
        classification_form = TransportClassificationSetupForm(
            instance=classification,
            prefix="classification",
        )

    return render(
        request,
        "internal/shipments/edit.html",
        {
            "shipment": shipment,
            "item": item,
            "classification": classification,
            "shipment_form": shipment_form,
            "item_form": item_form,
            "classification_form": classification_form,
        },
    )


@login_required


def _complete_document_checklist_items(shipment, document):
    """
    Mark checklist items related to this document as completed after upload.

    This does not mean final approval; it means the required document file
    is now available for internal review.
    """
    document_label = _shipment_document_label(document).lower()
    document_type = str(getattr(document, "document_type", "") or "").lower()
    document_type_text = document_type.replace("_", " ")

    updated = 0

    for item in shipment.checklist_items.all():
        label = str(getattr(item, "label", "") or "").lower()
        checklist_type = str(getattr(item, "checklist_type", "") or "").lower()

        if checklist_type not in ["document", "authorization"]:
            continue

        matches_label = document_label and document_label in label
        matches_type = document_type and document_type in label
        matches_type_text = document_type_text and document_type_text in label

        if matches_label or matches_type or matches_type_text:
            if hasattr(item, "is_completed"):
                item.is_completed = True
                update_fields = ["is_completed"]

                if hasattr(item, "completed_at"):
                    from django.utils import timezone
                    item.completed_at = timezone.now()
                    update_fields.append("completed_at")

                item.save(update_fields=update_fields)
                updated += 1

    return updated


def shipment_document_workspace_view(request, shipment_id, document_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)
    document = get_object_or_404(
        ShipmentDocument,
        id=document_id,
        shipment=shipment,
    )

    if request.method == "POST":
        action = request.POST.get("action", "").strip()

        if action == "upload_signed_file":
            uploaded_file = request.FILES.get("signed_file")

            if not uploaded_file:
                messages.error(request, "Selecione um arquivo preenchido/assinado para envio.")
                return redirect(
                    "shipment_document_workspace",
                    shipment_id=shipment.id,
                    document_id=document.id,
                )

            try:
                _save_document_upload(document, uploaded_file, actor=request.user)
                completed_items = _complete_document_checklist_items(shipment, document)

                ShipmentEvent.objects.create(
                    shipment=shipment,
                    event_type="updated",
                    actor=request.user,
                    notes=(
                        f"Document uploaded internally: {_shipment_document_label(document)}. "
                        f"Related checklist items completed: {completed_items}."
                    ),
                )

                messages.success(request, "Documento enviado para revisão interna.")
            except Exception as exc:
                messages.error(request, f"Não foi possível salvar o documento: {exc}")

            return redirect(
                "shipment_document_workspace",
                shipment_id=shipment.id,
                document_id=document.id,
            )

        if action == "request_correction":
            return redirect(
                "shipment_request_document_correction",
                shipment_id=shipment.id,
                document_id=document.id,
            )

    generated_file = _document_file_info(
        document,
        ["generated_file", "template_file", "file"],
    )
    signed_file = _document_file_info(
        document,
        ["signed_file", "uploaded_file"],
    )

    related_checklist_items = shipment.checklist_items.filter(
        label__icontains=_shipment_document_label(document).split(" ")[0]
    ).order_by("id")

    return render(
        request,
        _shipment_document_workspace_template(request),
        {
            "shipment": shipment,
            "document": document,
            "document_label": _shipment_document_label(document),
            "document_status_label": _shipment_document_status_label(document),
            "generated_file": generated_file,
            "signed_file": signed_file,
            "related_checklist_items": related_checklist_items,
            "classification": getattr(shipment, "classification", None),
            "items": shipment.items.all(),
        },
    )



@login_required
def shipment_document_workspace_view(request, shipment_id, document_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)
    document = get_object_or_404(
        ShipmentDocument,
        id=document_id,
        shipment=shipment,
    )

    schema = get_document_form_schema(document.document_type)

    form_data, _created = ShipmentDocumentFormData.objects.get_or_create(
        shipment=shipment,
        document=document,
        defaults={
            "document_type": document.document_type,
            "form_status": "required",
        },
    )

    initial_values = get_initial_values_from_shipment(
        shipment,
        document.document_type,
    )
    form_values = dict(initial_values)

    for key, value in (form_data.data_json or {}).items():
        if isinstance(value, bool):
            form_values[key] = value
        elif value not in [None, "", [], {}]:
            form_values[key] = value

    if request.method == "POST":
        action = request.POST.get("action", "").strip()

        if action in ["save_form", "generate_document"]:
            submitted_values = extract_form_values(schema, request.POST)

            form_data.data_json = submitted_values
            form_data.updated_by = request.user
            form_data.form_status = "form_saved"

            if action == "generate_document":
                generated_html = render_document_html(
                    document=document,
                    shipment=shipment,
                    schema=schema,
                    values=submitted_values,
                )
                form_data.generated_html = generated_html
                form_data.form_status = "generated"
                form_data.generated_at = timezone.now()

            form_data.save()

            if action == "generate_document":
                messages.success(request, "Generated document. Abra a prévia para imprimir/salvar como PDF.")
            else:
                messages.success(request, "Form saved.")

            return redirect(
                "shipment_document_workspace",
                shipment_id=shipment.id,
                document_id=document.id,
            )

        if action == "upload_signed_file":
            uploaded_file = request.FILES.get("signed_file")

            if not uploaded_file:
                messages.error(request, "Selecione um arquivo preenchido/assinado para envio.")
                return redirect(
                    "shipment_document_workspace",
                    shipment_id=shipment.id,
                    document_id=document.id,
                )

            form_data.signed_file.save(
                uploaded_file.name,
                uploaded_file,
                save=False,
            )
            form_data.form_status = "signed_uploaded"
            form_data.uploaded_at = timezone.now()
            form_data.updated_by = request.user
            form_data.save()

            document_update_fields = []

            if hasattr(document, "signed_file"):
                # Reuse the same stored file instead of writing a duplicate.
                document.signed_file.name = form_data.signed_file.name
                document_update_fields.append("signed_file")

            if hasattr(document, "signed_at"):
                document.signed_at = form_data.uploaded_at
                document_update_fields.append("signed_at")

            if hasattr(document, "uploaded_by"):
                document.uploaded_by = request.user
                document_update_fields.append("uploaded_by")

            if hasattr(document, "status"):
                available_statuses = [
                    value
                    for value, _label
                    in document._meta.get_field("status").choices
                ]

                for candidate in [
                    "uploaded",
                    "signed",
                    "waiting_signature",
                    "draft",
                ]:
                    if candidate in available_statuses:
                        document.status = candidate
                        document_update_fields.append("status")
                        break

            if document_update_fields:
                document.save(
                    update_fields=list(
                        dict.fromkeys(document_update_fields)
                    )
                )

            if (
                hasattr(document, "update_hashes")
                and getattr(document, "signed_file", None)
            ):
                document.update_hashes(save=True)

            ShipmentEvent.objects.create(
                shipment=shipment,
                event_type="updated",
                actor=request.user,
                notes=f"Signed/completed document uploaded: {document.document_type}.",
            )

            messages.success(request, "Documento assinado/enviado para revisão interna.")

            return redirect(
                "shipment_document_workspace",
                shipment_id=shipment.id,
                document_id=document.id,
            )

    return render(
        request,
        _shipment_document_workspace_template(request),
        {
            "shipment": shipment,
            "document": document,
            "form_data": form_data,
            "schema": schema,
            "form_values": form_values,
            "items": shipment.items.all(),
            "classification": getattr(shipment, "classification", None),
            "has_generated_document": bool(form_data.generated_html),
            "has_signed_file": bool(
                document_signed_file(document)
            ),
            "signed_file_url": (
                document_signed_file(document).url
                if document_signed_file(document)
                else ""
            ),
        },
    )


@login_required
def shipment_generated_document_view(request, shipment_id, document_id):
    shipment = get_object_or_404(visible_shipments_for_user(request.user), id=shipment_id)
    document = get_object_or_404(
        ShipmentDocument,
        id=document_id,
        shipment=shipment,
    )
    form_data = get_object_or_404(
        ShipmentDocumentFormData,
        shipment=shipment,
        document=document,
    )

    if not form_data.generated_html:
        messages.error(request, "This document has not been generated yet.")
        return redirect(
            "shipment_document_workspace",
            shipment_id=shipment.id,
            document_id=document.id,
        )

    return HttpResponse(form_data.generated_html)



@login_required
def shipments_dashboard_view(request):
    """
    Aggregated dashboard for shipment, transport, custody, document readiness
    and operational checklist tracking.
    """
    qs = (
        visible_shipments_for_user(request.user)
        .select_related("origin_biobank", "destination_biobank", "requested_by")
        .prefetch_related("items", "documents", "checklist_items")
        .order_by("-created_at")
    )

    total_shipments = qs.count()

    documents_qs = ShipmentDocument.objects.filter(shipment__in=qs)
    checklist_qs = ShipmentChecklistItem.objects.filter(shipment__in=qs)
    events_qs = (
        ShipmentEvent.objects
        .select_related("shipment", "actor")
        .filter(shipment__in=qs)
        .order_by("-created_at", "-id")
    )

    status_summary = []
    for value, label in Shipment.STATUS_CHOICES:
        count = qs.filter(status=value).count()
        if count:
            status_summary.append({
                "value": value,
                "label": label,
                "total": count,
            })

    flow_summary = []
    for value, label in Shipment.FLOW_TYPES:
        count = qs.filter(flow_type=value).count()
        if count:
            flow_summary.append({
                "value": value,
                "label": label,
                "total": count,
            })

    document_pending_statuses = [
        "pending",
        "required",
        "draft",
        "form_saved",
        "generated",
        "under_review",
        "submitted",
        "correction_requested",
        "rejected",
    ]

    ready_or_active = qs.exclude(status__in=["cancelled", "received", "completed"]).count()
    received_or_completed = qs.filter(status__in=["received", "completed"]).count()
    document_pending = qs.filter(documents__status__in=document_pending_statuses).distinct().count()
    ready_for_dispatch = qs.filter(status="ready_for_dispatch").count()

    document_total = documents_qs.count()
    document_draft = documents_qs.filter(status__in=["pending", "required", "draft", "form_saved", "generated"]).count()
    document_uploaded = documents_qs.filter(status__in=["uploaded", "signed_uploaded", "under_review", "submitted"]).count()
    document_approved = documents_qs.filter(status="approved").count()

    checklist_total = checklist_qs.count()
    checklist_completed = checklist_qs.filter(is_completed=True).count()
    checklist_pending = checklist_qs.filter(is_required=True, is_completed=False).count()

    ctx = base_context(request)
    ctx.update({
        "total_shipments": total_shipments,
        "ready_or_active": ready_or_active,
        "received_or_completed": received_or_completed,
        "document_pending": document_pending,
        "ready_for_dispatch": ready_for_dispatch,
        "document_total": document_total,
        "document_draft": document_draft,
        "document_uploaded": document_uploaded,
        "document_approved": document_approved,
        "checklist_total": checklist_total,
        "checklist_completed": checklist_completed,
        "checklist_pending": checklist_pending,
        "status_summary": status_summary,
        "flow_summary": flow_summary,
        "document_status_summary": list(
            documents_qs.values("status")
            .annotate(total=Count("id"))
            .order_by("status")
        ),
        "checklist_summary": list(
            checklist_qs.values("checklist_type", "is_completed")
            .annotate(total=Count("id"))
            .order_by("checklist_type", "is_completed")
        ),
        "origin_counts": qs.values("origin_biobank__name")
            .annotate(total=Count("id"))
            .order_by("-total", "origin_biobank__name")[:8],
        "destination_counts": qs.values("destination_biobank__name")
            .annotate(total=Count("id"))
            .order_by("-total", "destination_biobank__name")[:8],
        "recent_shipments": qs[:10],
        "recent_events": events_qs[:10],
    })

    return render(request, "internal/shipments/dashboard.html", ctx)

def _shipment_document_workspace_template(request):
    """Select the classic or experimental wizard workspace."""
    if request.GET.get("ui") == "wizard":
        return "internal/shipments/document_workspace_wizard.html"

    return "internal/shipments/document_workspace.html"

